#!/bin/sh -e

# Included initramfs shuts down / reboots according to parameters
kname=/usr/local/boot/kernel-kexec.zi

# RAM wiping options
# memtest=1: 0x00 once
# memtest=2: 0x00, 0xff, 0x00
# memtest=3: 0x00, 0xff, 0x55, 0x00
wipeopt="quiet memtest=2"


kexecopt="-l ${kname}"

case "$1" in
    arm)
        kexec ${kexecopt} --append="${wipeopt} halt alert"
        ;;

    halt)
        kexec ${kexecopt} --append="${wipeopt} halt"
        ;;

    reboot)
        kexec ${kexecopt} --append="${wipeopt}"
        ;;

    unload)
        kexec -u
        ;;

    *)
        echo "$0 arm|halt|reboot|unload"
        exit 1
        ;;
esac
