#!/bin/sh -e

# 32-bit (LOWMEM-only memtest) and 64-bit kernels
# Included initramfs shuts down / reboots according to parameters
kname=/usr/local/boot/kernel-kexec.zi
kname64=/usr/local/boot/kernel-kexec-64.zi

# RAM wiping options
# memtest=1: 0x00 once
# memtest=2: 0x00, 0xff, 0x00
# memtest=3: 0x00, 0xff, 0x55, 0x00
wipeopt="quiet memtest=2"


# Checks whether CPU has 64-bit support (amd64)
has_lm() {
    grep -q '^flags\>.*\<lm\>' /proc/cpuinfo
}


# Use 64-bit KEXEC kernel on supporting CPUs, so that
# memtest is not limited to LOWMEM (Kernel: #42630)
if has_lm; then
    kname=${kname64}
fi


kexecopt="-l ${kname}"

case "$1" in
    arm)
        kexec ${kexecopt} --append="${wipeopt} halt alert"
        ;;

    halt)
        kexec ${kexecopt} --append="${wipeopt} halt"
        ;;

    reboot)
        kexec ${kexecopt} --append="${wipeopt}"
        ;;

    unload)
        kexec -u
        ;;

    *)
        echo "$0 arm|halt|reboot|unload"
        exit 1
        ;;
esac
