#!/bin/sh -e

# This program can be safely run via sudo

sysrq=/proc/sys/kernel/sysrq

if [ ! -e ${sysrq} ]; then
    echo "SysRq control file not found"
    exit 1
fi

if [ $# != 1 -o \( x"$1" != x0 -a x"$1" != x1 \) ]; then
    echo "Format: sudo sysrq 0|1"
    exit 1
fi

echo "$1" > ${sysrq}
