#!/bin/sh -e

passed=0
failed=0


stest() {
    local exp="$1"
    local desc="$2"
    local res=
    shift 2

    echo "----------------------------------------"
    echo "Testing (exp: ${exp}): ${desc}"
    if "$@" </dev/null 1>/dev/null 2>&1; then
        res=pass
    else
        res=fail
    fi

    if [ ${exp} = ${res} ]; then
        echo "Result: OK"
        passed=$((passed+1))
    else
        echo "Result: *** BAD ***"
        echo "Command: $@"
        failed=$((failed+1))
    fi
}


if [ `id -u` != 0  -o  `id -g` != 0 ]; then
    echo "Must be root"
    exit 1
fi

if ! /etc/init.d/tor -q status || ! /etc/init.d/cabled -q status; then
    echo "Tor and cables daemons must be running"
    exit 1
fi


webhost=torproject.org
webip=38.229.72.16

tlsdatehost=https://www.google.com
onionhost=3g2upl4pq6kufc4m.onion

ccuser=`cat /home/anon/persist/security/cable/certs/username`
cctor=`cat /home/anon/persist/security/tor/hidden_service/hostname`


# Check that wireless MAC addresses were changed
for netdev in /sys/class/net/*; do
    if iwconfig "${netdev}" 1>/dev/null 2>&1 && [ -e "${netdev}"/phy80211 ]; then
        wmachw=`cat "${netdev}"/phy80211/macaddress`
        wmac=`cat "${netdev}"/address`
        stest pass "Changed MAC: `basename ${netdev}`" [ ${#wmachw} = ${#wmac} -a "${wmachw}" != "${wmac}" ]
    fi
done


# Clearnet access via HTTP/SOCKS/direct
stest fail "Fetch .org via HTTP proxy as root"                     curl -fsSI -x 127.0.0.1:8118                ${webhost}
stest fail "Fetch .org via HTTP proxy as nofw"     sudo -n -u nofw curl -fsSI -x 127.0.0.1:8118                ${webhost}
stest pass "Fetch .org via HTTP proxy as anon"     sudo -n -u anon curl -fsSI -x 127.0.0.1:8118                ${webhost}
stest pass "Fetch .org via HTTP proxy as cable"    sudo -n -u cable curl -fsSI -x 127.0.0.1:8118               ${webhost}
stest fail "Fetch .org via SOCKS proxy as root"                    curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy as nofw"    sudo -n -u nofw curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy as cable"   sudo -n -u cable curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest pass "Fetch .org via SOCKS proxy as anon"    sudo -n -u anon curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest pass "Fetch .org via SOCKS proxy as privoxy" sudo -n -u privoxy curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as root"                 curl -fsSI --socks5 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as nofw" sudo -n -u nofw curl -fsSI --socks5 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as anon" sudo -n -u anon curl -fsSI --socks5 127.0.0.1:9050 ${webhost}
stest fail "Fetch .org via SOCKS proxy w/ local DNS as privoxy" sudo -n -u privoxy curl -fsSI --socks5 127.0.0.1:9050 ${webhost}

# Clearnet access w/o proxy
stest fail "Fetch .org w/o proxy as root"                          curl -fsSI -x "" ${webhost}
stest pass "Fetch .org w/o proxy as nofw"          sudo -n -u nofw curl -fsSI -x "" ${webhost}
stest fail "Fetch .org w/o proxy as anon"          sudo -n -u anon curl -fsSI -x "" ${webhost}
stest fail "Fetch .org w/o proxy as tor"           sudo -n -u tor  curl -fsSI -x "" ${webhost}

stest fail "Fetch tlsdate w/o proxy as anon"       sudo -n -u anon    curl -fsSI -x "" ${tlsdatehost}
stest pass "Fetch tlsdate w/o proxy as tlsdate"    sudo -n -u tlsdate curl -fsSI -x "" ${tlsdatehost}

# Darknet access via HTTP/SOCKS
stest pass "Fetch .onion via HTTP  proxy as anon"  sudo -n -u anon curl -fsSI -x 127.0.0.1:8118                ${onionhost}
stest pass "Fetch .onion via SOCKS proxy as anon"  sudo -n -u anon curl -fsSI --socks5-hostname 127.0.0.1:9050 ${onionhost}

# Clearnet IP access via HTTP/SOCKS/direct (SOCKS4=fail <-> SafeSocks=1)
stest pass "Fetch IP via HTTP proxy as anon"       sudo -n -u anon curl -fsSI -x 127.0.0.1:8118                ${webip}
stest pass "Fetch IP via SOCKS proxy as anon"      sudo -n -u anon curl -fsSI --socks5-hostname 127.0.0.1:9050 ${webip}
stest pass "Fetch IP via SOCKS4 proxy as anon"     sudo -n -u anon curl -fsSI --socks4          127.0.0.1:9050 ${webip}
stest fail "Fetch IP w/o proxy as root"                            curl -fsSI -x ""                            ${webip}
stest fail "Fetch IP w/o proxy as anon"            sudo -n -u anon curl -fsSI -x ""                            ${webip}
stest fail "Fetch IP w/o proxy as privoxy"         sudo -n -u privoxy curl -fsSI -x ""                         ${webip}
stest pass "Fetch IP w/o proxy as tor"             sudo -n -u tor  curl -fsSI -x ""                            ${webip}
stest pass "Fetch IP w/o proxy as nofw"            sudo -n -u nofw curl -fsSI -x ""                            ${webip}


# Tor control port access
stest fail "Access Tor control port as root"                       nc -q 0 127.0.0.1 9051
stest fail "Access Tor control port as anon"       sudo -n -u anon nc -q 0 127.0.0.1 9051
stest pass "Access Tor control port as tor"        sudo -n -u tor  nc -q 0 127.0.0.1 9051
stest pass "Invoke tor-ctrl"                       sudo -n -u tor  tor-ctrl status


# Cables communication service server access
stest fail "Fetch CC service as root"                              curl -fsSI -x "" 127.0.0.1:9080/${ccuser}/request/ver
stest fail "Fetch CC service as anon"              sudo -n -u anon curl -fsSI -x "" 127.0.0.1:9080/${ccuser}/request/ver
stest fail "Fetch CC service as nofw"              sudo -n -u anon curl -fsSI -x "" 127.0.0.1:9080/${ccuser}/request/ver
stest pass "Fetch CC service as tor"               sudo -n -u tor  curl -fsSI -x "" 127.0.0.1:9080/${ccuser}/request/ver

# Cables communication ping
stest pass "CC-ping @tor as anon"                  sudo -n -u anon cable-ping ${ccuser}@${cctor}

# Cables communication mail sending
ccsend() {
    local desc="$1"
    local from="$2"
    local to1="$3"

    cable-send <<EOF
From: Anon Anon <${from}>
To: Anon Anon <${to1}>
Subject: Test (${desc})

Test
EOF
}

stest pass "Send cable to self (Tor -> Tor)" ccsend "Tor -> Tor" ${ccuser}@${cctor} ${ccuser}@${cctor}
stest fail "Bogus cable host"                ccsend "Bogus"      ${ccuser}@bogus    ${ccuser}@${cctor}
stest fail "Bogus cable username"            ccsend "Bogus"      ${ccuser}@${cctor} bogus@${cctor}
echo "NOTE: 2 messages should be delivered to user mailbox"


# Done
stest pass "Done" :
echo "passed: ${passed}, failed: ${failed}"
