#!/bin/sh -e

umask 077


# This command is run via "sudo -u nofw"
# Available environment: HOME, USER

# Some sanity checks
if [ "${HOME}" != /home/nofw ]; then
    echo "This program should be run via sudo"
    exit 1
fi

refdir=/mnt/live${HOME}
if [ ! -e ${refdir} ]; then
    echo "Could not locate reference directory"
    exit 1
fi


# Reinitialize home directory
rsync -aHAXS -x --delete-excluded ${refdir}/ ${HOME}


# Rely on pam_mktemp (sudo doesn't pass default variables)
export TMPDIR=/tmp/.private/${USER}

# Setup environment
unset XAUTHORITY
export TZ=:UTC
export XDG_CONFIG_HOME=${HOME}/config
export XDG_DATA_HOME=${XDG_CONFIG_HOME}/local
export XDG_CACHE_HOME=${TMPDIR}/cache
export GTK2_RC_FILES=${XDG_CONFIG_HOME}/gtk-2.0/gtkrc

# NOTE: GStreamer only works if nofw can access /dev/snd/*
# (mirrors /etc/env.d/99gstreamer)
export GST_REGISTRY=/var/cache/gstreamer/registry.bin
export GST_REGISTRY_UPDATE=no


# Run Midori (which uses getpwent instead of ${HOME})
set +e
midori -c ${XDG_CONFIG_HOME}/midori


# Reinitialize home directory
# (rm fails to rmdir ${USER} from /tmp/.private)
rsync -aHAXS -x --delete-excluded ${refdir}/ ${HOME}
rm -rf --one-file-system ${TMPDIR} 2>/dev/null
