#!/bin/sh -e

umask 077


# This command is run via "sudo -u nofw"
# Available environment: HOME, USER

# pam_namespace takes care of reinitializing directories


# Some sanity checks
if [ "${HOME}" != /home/nofw ]; then
    echo "This program should be run via sudo"
    exit 1
fi


# Rely on pam_mktemp (sudo doesn't pass default variables)
export TMPDIR=/tmp/.private/${USER}

# Setup environment
unset XAUTHORITY
export TZ=:UTC
export XDG_CONFIG_HOME=${HOME}/config
export XDG_DATA_HOME=${XDG_CONFIG_HOME}/local
export XDG_CACHE_HOME=${TMPDIR}/cache
export DCONF_PROFILE=${USER}
export GTK2_RC_FILES=${XDG_CONFIG_HOME}/gtk-2.0/gtkrc
export GSETTINGS_BACKEND=dconf

# NOTE: GStreamer only works if nofw can access /dev/snd/*
# (mirrors /etc/env.d/99gstreamer)
export GST_REGISTRY=/var/cache/gstreamer/registry.bin
export GST_REGISTRY_UPDATE=no


# Run browser
exec firefox file:///home/nofw/info/warning.html
