#!/bin/bash -e

sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}


rezip() {
    zip=$1
    dir=${zip}.tmp

    unzip -qd ${dir} ${zip}
    rm ${zip}
    (cd ${dir}; zip -qrm0 ../`basename ${zip}` .)
    rmdir ${dir}
}

regzip() {
    gz=$1

    # -0 switch is unique to pigz
    gunzip  ${gz}
    gzip -0 ${gz%.gz}
}


# Sanity check
if [ ${PHASE} != copy ]; then
    echo "This is phase [${PHASE}], run $0 in phase [copy]."
    exit 1
fi


sinfo "Cleaning up portage configuration"
sed -i /TEMP/d /var/lib/portage/world /etc/portage/package.use


# equery requires gentoolkit, so copy ebuilds early
# NOTE: the below patches are intended for depclean
#
# python:  portage, xcb-proto, libglade, gtk+, gucharmap, glib, exiv2, pidgin, mesa,
#          gobject-introspection, openbox, totem
# perl:    gentoolkit, lm_sensors, graphicsmagick, eboard, xdg-utils, pptpclient
# cpio:    splashutils
# debianutils:     ca-certificates
# java:            jamvm
# xorg fonts:      font-misc-meltho
# gst-plugins-bad: gst-plugins-vp8
sinfo "Patching copies of selected ebuilds"
ebuilds="app-misc/ca-certificates
         app-portage/gentoolkit
         dev-java/jamvm
         dev-libs/glib
         dev-libs/gobject-introspection
         games-board/eboard
         gnome-base/libglade
         gnome-extra/gucharmap
         media-fonts/font-misc-meltho
         media-gfx/exiv2
         media-gfx/graphicsmagick
         media-gfx/splashutils
         media-libs/mesa
         media-plugins/gst-plugins-vp8
         media-video/totem
         net-dialup/pptpclient
         net-im/pidgin
         sys-apps/lm_sensors
         sys-apps/portage
         x11-libs/gtk+
         x11-misc/xdg-utils
         x11-proto/xcb-proto
         x11-wm/openbox"

# /usr/portage is bind-mounted ro
for ebuild in ${ebuilds}; do
    rsync -a /usr/portage/${ebuild} /usr/local/portage/`dirname ${ebuild}`
    eval ebuild_`basename ${ebuild//[-+]}`=`equery which ${ebuild}`
done

# Make portage think it doesn't need Python
# (allows depclean after python unmerge + shadow copy)
sed -i 's/\${python_dep}//' ${ebuild_portage}

# Perl is not needed at all by gentoolkit and eboard
# Perl is only needed by sensors-detect and sensors-conf-convert
# Perl is not needed for pptpclient when used by networkmanager-pptp
sed -i s:dev-lang/perl:: ${ebuild_gentoolkit} ${ebuild_eboard} ${ebuild_lm_sensors} \
                         ${ebuild_pptpclient}

# Python is only (possibly) needed during libxcb build
# Python is only needed by libglade-convert
# Python is not needed at all by gtk+, gucharmap, glib, exiv2 and totem
# Python is only needed by g-ir-{scanner,annotation-tool}
sed -i 's:^\(inherit\>.*\) python\>:\1:' ${ebuild_xcbproto} ${ebuild_libglade} \
                                         ${ebuild_gtk} ${ebuild_gucharmap} ${ebuild_glib} \
                                         ${ebuild_exiv2} ${ebuild_gobjectintrospection} \
                                         ${ebuild_totem}

# Python is needed by dbus-python, which is a non-separated dependency in ebuild
sed -i 's:\<dev-python/dbus-python\>::' ${ebuild_pidgin}

# Python is only needed for openbox-xdg-autostart
sed -i 's:\<dev-python/pyxdg\>::' ${ebuild_openbox}

# Python support in libxml2 is only needed in development tools
sed -i 's:\(dev-libs/libxml2\)\[python\]:\1:' ${ebuild_mesa}

# cpio is only needed for splash_geninitramfs
sed -i s:app-arch/cpio:: ${ebuild_splashutils}

# perl-module.eclass: disable unnecessary dev-lang/perl[-build] dependency
sed -i 's/^inherit /GENTOO_DEPEND_ON_PERL="no"\n&/' ${ebuild_graphicsmagick}

# Perl is needed by mimeopen (File-MimeInfo), which is an optional dependency
sed -i 's:\<dev-perl/File-MimeInfo\>::' ${ebuild_xdgutils}

# debianutils are only needed for update-ca-certificates
sed -i 's:\<sys-apps/debianutils\>::' ${ebuild_cacertificates}

# javac/javadoc dependencies are only for symlinks in /usr/bin
sed -i 's:^\(inherit\>.*\) java-vm-2\>:\1:; s:\<dev-java/gjdoc\>::; s:\<dev-java/eclipse-ecj\>::' ${ebuild_jamvm}

# xorg-2 brings dependency on encodings/mkfontdir/mkfontscale
sed -i 's:^inherit xorg-2$:SLOT="0":; s:^IUSE=""$:IUSE="X":' ${ebuild_fontmiscmeltho}

# only libgstbasevideo is needed from gst-plugins-bad
sed -i 's:>=media-libs/gst-plugins-bad-[^[:blank:]"]*::' ${ebuild_gstpluginsvp8}
sed -i '\:/usr/lib/libgstbasevideo\>:d' /var/db/pkg/media-libs/gst-plugins-bad-*/CONTENTS

for ebuild in ${!ebuild_*}; do
    eval ebuild=\$${ebuild}
    ebuild ${ebuild} manifest
    echo liberte > /var/db/pkg/`echo ${ebuild%.ebuild} | cut -d/ -f5,7`/repository
done
rm -f /var/cache/edb/vdb_*.pickle

# Packages wrongly rdepend on gettext instead of libintl (provided by glibc)
echo sys-devel/gettext-0.15 >> /etc/portage/profile/package.provided

# java-config wrappers are superfluous for minimal VMs (and require Python)
echo dev-java/java-config-2.1.11 >> /etc/portage/profile/package.provided

# virtualbox-guest-additions unnecessarily depends on xf86-video-virtualbox
equery which app-emulation/virtualbox-guest-additions \
    | sed 's:^.*/virtualbox-guest-additions:x11-drivers/xf86-video-virtualbox:; s:\.ebuild$::' \
    >> /etc/portage/profile/package.provided


# This recompiles packages with TEMP flags in package.use
sinfo "Recompiling build-dependent packages"
emerge -quDN @world


# Unmerge non-runtime dependencies (and cleanup the kernel directory)
sinfo "Unmerging build and temporary dependencies"
emerge -qc --with-bdeps n


sinfo "Copying gcc shared libs"
rsync -aHS `find /usr/lib/gcc -name '*.so' -o -name '*.so.*'` /usr/lib/
ldconfig

echo sys-devel/libtool-2.2.10 >> /etc/portage/profile/package.provided
sed -i '\:/usr/lib/libltdl\>:d' /var/db/pkg/sys-devel/libtool-*/CONTENTS


# Unmerge some packages that are listed in the system profile
# No package can be emerged afterwards
sinfo "Unmerging development packages"

emerge -qC \
    sys-devel/make      \
    sys-devel/gnuconfig \
    sys-devel/patch     \
    \
    sys-devel/gcc       \
    sys-devel/binutils  \
    \
    virtual/os-headers       \
    sys-kernel/linux-headers \
    sys-apps/busybox         \
    \
    virtual/man         \
    sys-apps/man        \
    sys-apps/man-pages  \
    sys-apps/texinfo    \
    \
    app-arch/cpio

rm -rf /usr/share/{binutils-data,gcc-data}/
rm -f /usr/lib/{?,}crt?.o


sinfo "Unmerging orphaned packages"
emerge -qc --with-bdeps n


if [ -e /usr/bin/perl ]; then
    sinfo "Failed to discard Perl dependencies"
    false
fi

if [ -e /usr/bin/gettext ]; then
    sinfo "Failed to discard gettext dependencies"
    false
fi

if [ -e /usr/bin/run-java-tool  -o  -e /usr/bin/java-config ]; then
    sinfo "Failed to discard Java dependencies"
    false
fi


sinfo "Fixing .la files"
rm /usr/lib/libGraphicsMagick*.la /usr/lib/libsox.la
for mod in `find /usr/lib/GraphicsMagick* -name '*.so'`; do
    echo dlname=\'${mod##*/}\' > ${mod%.so}.la
done


# Not necessary anymore?
if [ -e /etc/gtk-2.0/gtk.immodules ]; then
    sinfo "Fixing gtk.immodules"
    mv /etc/gtk-2.0/gtk.immodules /etc/gtk-2.0/`portageq envvar CHOST`/
fi

if [ -e /etc/gtk-2.0/gdk-pixbuf.loaders ]; then
    sinfo "Removing deprecated gdk-pixbuf.loaders"
    rm /etc/gtk-2.0/gdk-pixbuf.loaders
fi


sinfo "Fixing Murrine themes for GTK-2"
sed -i 's/_ratio\>/_shade/; /\<\(scrollbar_color\|gradients\)\>[[:blank:]]*=/d' \
    /usr/share/themes/{Murr*,NOX}/gtk-2.0/gtkrc


# Any problem will cause a fatal error
sinfo "Checking linking consistency"
revdep-rebuild -qi


# Unmerge portage utilities (revdep-rebuild is unavailable afterwards)
sinfo "Unmerging portage tools"
emerge -qC app-portage/gentoolkit


sinfo "Faking Python removal"
dbpython=`mktemp -d`
mv /var/db/pkg/dev-lang/python-* ${dbpython}/python


sinfo "Unmerging orphaned packages"
emerge -qc --with-bdeps n

if [ -e /usr/sbin/python-updater ]; then
    sinfo "Failed to discard Python dependencies"
    false
fi


# Unmerge packages that other package depend upon, but are not needed
# ("emerge -c" cannot be used afterwards)
# Dependencies:
# sandbox        - xz-utils, pax-utils
# portage        - python, sandbox, pax-utils, rsync
sinfo "Unmerging unnecessary packages"
emerge -qC sys-apps/sandbox


sinfo "Updating environment"
env-update


sinfo "Unmerging portage"
sed -i '\:^... /usr/lib/portage/:d' /var/db/pkg/sys-apps/`echo ${ebuild_portage} | sed 's:.*/::; s:\.ebuild$::'`/CONTENTS
FEATURES="${FEATURES} -sandbox -usersandbox" ebuild ${ebuild_portage} unmerge 1>/dev/null
rm -r /usr/lib/portage/


sinfo "Actually removing Python"
rm -f `awk '! /^dir / { print $2 }' ${dbpython}/python/CONTENTS`
rm -r /usr/lib/python*/
rm -r ${dbpython}


sinfo "Verifying HTP servers"
htpservers=`sed -n 's/^SERVERS="\(.*\)"$/\1/p' /etc/conf.d/htpdate`
htpdates=
for htp in ${htpservers}; do
    echo -ne "${htp}:\t"

    # Will fail if the server doesn't provide a timestamp
    htpdate=`curl -sI ${htp} | grep '^Date: ' | sed 's/^Date: //'`
    echo "${htpdate}"

    htpdates="${htpdates} "`date +%s -ud "${htpdate}"`
done

htpmin=`echo ${htpdates} | tr ' ' '\n' | sort -n | head -n 1`
htpmax=`echo ${htpdates} | tr ' ' '\n' | sort -n | tail -n 1`

if [ $((htpmax - htpmin)) -gt 60 ]; then
    echo "HTP servers disagreement > 1min, fix /etc/conf.d/htpdate"
    false
fi


# Done here because cache may be recreated after "src" phase
sinfo "Trimming icons directories and cache"
for theme in /usr/share/icons/*/index.theme; do
    find `dirname ${theme}` -maxdepth 1 \( -name '[5-9][0-9]x*' -o -name '[1-9][0-9][0-9]x*' \) -exec rm -r {} \;

    awk '/^\[/ { x=1; if(match($0,/^\[([0-9]+)x/,ar) != 0 && ar[1]>48) x=42; } { if (x!=42) print; }' ${theme} \
        | sed 's/,\([5-9][0-9]\|[1-9][0-9][0-9]\)x[^,]*//g; s/\(=16,22,32,48\),.*/\1/' > ${theme}.new
    mv ${theme}.new ${theme}
done

find /usr/share/icons -mindepth 1 -maxdepth 1 -type d \
    -exec gtk-update-icon-cache -q -f -i    {} \;
find /usr/share -mindepth 3 -type d -name hicolor \
    -exec gtk-update-icon-cache -q -f -i -t {} \;


sinfo "Regenerating fonts cache"
fc-cache -fs


sinfo "Regenerating MIME and desktop DBs"
update-mime-database       /usr/share/mime
update-desktop-database -q /usr/share/applications


# http://www.freedesktop.org/wiki/Specifications/mime-actions-spec
sinfo "Modifying MIME actions ordering preferences"
sed -i 's/\<geeqie.desktop;gpicview.desktop;/gpicview.desktop;geeqie.desktop;/ ;
        s/\<epdfview.desktop;evince.desktop;/evince.desktop;epdfview.desktop;/ ;
        s/\<totem.desktop;audacious.desktop;/audacious.desktop;totem.desktop;/' \
    /usr/share/applications/mimeinfo.cache


# QuickTime (MP4) prevents HTML5 <video> from working
sinfo "Generating GStreamer cache"
rm -rf /var/cache/gstreamer
/usr/bin/gst-inspect* 1>/dev/null
chmod -R go=u,go-w /var/cache/gstreamer


sinfo "Generating GIO modules cache"
gio-querymodules /usr/lib/gio/modules


sinfo "Uncompressing selected files"
gunzip `find /usr/share/consolefonts -name '*.gz'` \
       `find /usr/share/keymaps      -name '*.gz'`

gunzip /usr/share/gedit-2/plugins/taglist/*.gz

rezip  /usr/gnu-classpath-[0-9]*/share/classpath/glibj.zip
rezip  /usr/lib/jamvm/classes.zip

rezip  /usr/share/zlibrary/hyphenationPatterns.zip
rezip  /usr/share/zlibrary/languagePatterns.zip
regzip /usr/share/zlibrary/unicode.xml.gz

rezip /usr/share/java-service-wrapper/lib/wrapper.jar
for jar in /opt/i2p/lib/*.jar /opt/i2p/webapps/*.war; do
    rezip ${jar}
done


# /lib/rc/plugins/splash.so can't be patched (fbsplashd)
sinfo "Substituting dynamic executables for splashutils"
ln -snf ../usr/sbin/fbsplashd      /sbin/fbsplashd.static
ln -snf ../usr/sbin/fbcondecor_ctl /sbin/fbcondecor_ctl.static
ln -snf ../usr/sbin/splash_util    /sbin/splash_util.static


sinfo "Removing invalid symlinks, dirs and files"
find / -xdev -type l ! -xtype f ! -xtype d ! -xtype c -delete
rmdir /usr/i686-pc-linux-gnu/{bin,lib,}

rm /etc/env.d/05binutils
rm /etc/env.d/05gcc-i686-pc-linux-gnu
rm -rf /etc/env.d/{binutils,gcc,python}
rm /etc/{init,conf,pam}.d/sshd

rm /usr/bin/{{i686-pc-linux-gnu-,}{gcc,g++,c++,cpp},cc,c89,c99,gcov}
rm /lib/cpp
rm /sbin/fix_libtool_files.sh

rm /usr/bin/{kernel,profile,python}-config
rm /usr/bin/python{,-wrapper}
rm /usr/share/eselect/modules/{binutils,kernel,news,profile,python}.eselect


sinfo "Tighting up SUID permissions"
chgrp cdrom     /usr/{bin/{cdrecord,cdda2wav,readcd},sbin/rscsi}
chmod u+s,o-rwx /usr/{bin/{cdrecord,cdda2wav,readcd},sbin/rscsi}


sinfo "Setting cables-related permissions"
chmod 710 /home/anon{,/persist{,/security{,/ssl},/mail,/cables}}


sinfo "Updating ld cache"
eselect env update 2>/dev/null
sed -i '/^export \(CONFIG_PROTECT\(_MASK\)\?\|MANPATH\|INFOPATH\|CVS_RSH\)=/d' /etc/profile.env


sinfo "Updating init scripts dependencies cache"
rc-update -u


sinfo "Setting sh (dash) and java (jamvm) symlinks"
ln -sf dash                          /bin/sh
ln -s  ../local/libexec/java.wrapper /usr/bin/java


# Spaces in entries are not handled, but it doesn't matter here
sinfo "Saving current packages list in /tmp/transient/pkg"
pakdir=/tmp/transient/pkg
mkdir -p ${pakdir}
for p in `find /var/db/pkg/ -mindepth 2 -maxdepth 2 -type d -printf '%P\n'`; do
    sed -n 's/^\(obj\|sym\) \([^ ]\+\).*$/\2/p' /var/db/pkg/${p}/CONTENTS > ${pakdir}/${p//\//=}
done


sinfo "Done."
