#!/bin/bash -e

helpdir=${HOME}/helpers
noroot="sudo -n -u nobody"

hsversion=`cat ${HOME}/config/kversion`
kversion=${hsversion/-/-hardened-}
[ ${kversion} != ${hsversion} ] || kversion=${hsversion}-hardened
xzmem=20

protected="/etc/._cfg????_locale.gen"


sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}

spatch() {
    local pname=$1; shift
    local pcat=cat
    local revok=

    if [ "${pname##*.}" = gz ]; then
        pcat=zcat
    fi

    revres=0
    ${pcat} ${pname} | patch --dry-run -R -Ns -r /tmp/patch-rejects "$@" 1>/dev/null || revres=$?

    if ${pcat} ${pname} | patch -Ns -r /tmp/patch-rejects "$@" 1>/dev/null; then
        echo "Successfully applied patch: ${pname}"
    else
        if [ ${revres} != 0 ]; then
            echo "Failed to apply patch: ${pname}"
            return 1
        else
            echo "Patch already applied: ${pname}"
        fi
    fi
    rm -f /tmp/patch-rejects
}

patch_ebuild() {
    spatch "$1" -p0
    ebuild `awk '{print $2; exit}' "$1"` manifest
}

rebuild_locales() {
    grep UTF-8 /usr/share/i18n/SUPPORTED > /etc/locale.gen.new
    if cmp -s /etc/locale.gen{.new,}; then
        rm /etc/locale.gen.new
    else
        sinfo "Rebuilding locales"
        mv /etc/locale.gen{.new,}
        locale-gen -q
    fi
}


# Sanity check
if [ ${PHASE} != src ]; then
    echo "This is phase [${PHASE}], run $0 in phase [src]."
    exit 1
fi


sinfo "Setting a hardened profile"
eselect profile set hardened/linux/x86

echo ">sys-kernel/hardened-sources-${hsversion}" > /etc/portage/package.mask/kernel
rm -f /etc/portage/savedconfig/*/*-[0-9]*


if [ -x /usr/bin/gpg  -a  -x /usr/bin/eix ]; then
    sinfo "Updating portage"

    gpg -q --homedir /etc/portage/gnupg --import /usr/local/addons/certs/gentoo-*.asc
    eix-sync -qw -C -q
fi


sinfo "Applying temporary portage patches"
# (#424816, VirtualBox: #11335)
patch_ebuild ${HOME}/patches/portage/virtualbox-guest-additions.patch
patch_ebuild ${HOME}/patches/portage/xf86-video-virtualbox.patch
# (#437446)
patch_ebuild ${HOME}/patches/portage/nip2.patch
# (#446514)
patch_ebuild ${HOME}/patches/portage/amd-ucode.patch
# (#448228, fixed in polkit-0.111)
patch_ebuild ${HOME}/patches/portage/polkit.patch


if [ "$1" = fresh  -o  ! -e /usr/src/linux-${kversion}/incremental ]; then
    sinfo "Compiling uname wrapper"
    gcc -ansi -Wall -pedantic -O2 -s -o /usr/local/bin/uname /usr/local/src/uname.c

    # Kernel sources should be present when sys-fs/udev is compiled,
    # also this part is often error-prone, so better do early.
    # Maintainer note: after non-fresh kernel update+compile, do
    # emerge -q1 app-emulation/{open-vm-tools-kmod,virtualbox-guest-additions}
    sinfo "Downloading kernel ${kversion}"
    rm -rf /usr/src/linux-${kversion} /lib/modules
    emerge -q1 =sys-kernel/hardened-sources-${hsversion}


    sinfo "Preparing kernel build environments"
    rm -rf /usr/src/linux-{main,kexec{,-64}}
    mkdir  /usr/src/linux-{main,kexec{,-64}}

    cp ${HOME}/config/linux-${kversion%-r*}.config          /usr/src/linux-main/.config
    cp ${HOME}/config/linux-${kversion%-r*}-kexec.config    /usr/src/linux-kexec/.config
    cp ${HOME}/config/linux-${kversion%-r*}-kexec-64.config /usr/src/linux-kexec-64/.config

    chown -hR bin:bin /usr/src/linux-{main,kexec{,-64}}


    # https://git.kernel.org/cgit/linux/kernel/git/mszeredi/vfs.git/diff/?id=overlayfs.v17&id2=f6161aa153581da4a3867a2d1a7caf4be19b6ec9
    # https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=04b00bdb41d0fd8d9cf3b146e334369cc2b0acdc
    # (#480548)
    sinfo "Applying kernel patches"
    spatch ${HOME}/patches/kernel/overlayfs.v17.patch  -d /usr/src/linux-${kversion} -p1
    spatch ${HOME}/patches/kernel/x509-long-form.patch -d /usr/src/linux-${kversion} -p1
    sed -i 's/reset_page_mapcount/page_mapcount_reset/' /usr/src/linux-${kversion}/mm/slob.c


    # Filter locales before remerging libc
    sinfo "Filtering locales"
    grep UTF-8 /usr/share/i18n/SUPPORTED > /etc/locale.gen


    # Some news are delayed until first emerge
    eselect news read all
    eselect news purge


    sinfo "Recompiling toolchain"
    oldgcc=`find /var/db/pkg/sys-devel -maxdepth 1 -type d -name 'gcc-[0-9]*'`
    emerge -q1 sys-devel/binutils
    emerge -q1 sys-devel/gcc

    # consider removing old gcc only if it still exists after emerge
    # (emerge was in a new slot, or same version)
    if [ -e "${oldgcc}" ]; then
        chost=`portageq envvar CHOST`
        oldgccprof=`gcc-config -c`
        newgccprof=`find /etc/env.d/gcc -type f -name "${chost}-*"           \
            ! -name "${oldgccprof}" ! -name "${oldgccprof}-*" -printf '%f\n' \
            | sort | head -n 1`

        # unmerge only if the "new" gcc has a different version
        if [ -n "${newgccprof}" ]; then
            gcc-config "${newgccprof}"
            emerge -qC --deselect=n =sys-devel/`basename ${oldgcc}`
        fi
    fi
    env-update
    source /etc/profile

    # necessary after gcc upgrades
    emerge -q1 sys-devel/libtool

    emerge -q1 sys-libs/glibc
    rm -f ${protected}


    # Rely on timezone-data ebuild updating /etc/localtime
    sinfo "Compiling system"
    touch /tmp/system-build
    USE="-X -consolekit" emerge -qeupv @system
    USE="-X -consolekit" emerge -qeu   @system
    rm -f ${protected}
    rebuild_locales

    # Also rebuild hardened-sources dependencies (#461848)
    emerge -q1 sys-devel/bc


    sinfo "Removing non-system packages"
    mv /etc/portage/sets/all{,.off}
    echo sys-kernel/hardened-sources > /etc/portage/sets/all
    emerge -qc --deselect=n
    mv /etc/portage/sets/all{.off,}


    sinfo "Checking for non-rebuilt packages"
    orphans=`find /var/db/pkg -mindepth 3 -maxdepth 3 -name BUILD_TIME           \
        ! -path  /var/db/pkg/sys-kernel/hardened-sources-${hsversion}/BUILD_TIME \
        ! -newer /tmp/system-build -printf '%h\n' | sed s:/var/db/pkg/:: | sort`
    if [ -n "${orphans}" ]; then
        sinfo "The following packages were not rebuilt"
        echo "${orphans}"
        exit 1
    fi
    rm /tmp/system-build


    sinfo "Preparing kernel"
    ${helpdir}/gen-kernel prepare


    sinfo "Marking tree as ready for incremental builds"
    touch /usr/src/linux-${kversion}/incremental


    # Shouldn't contain any rebuilds
    sinfo "Listing updates"
    emerge -qupvDN --with-bdeps y @world

else
    sinfo "Skipping full rebuild (use \"fresh\")"
    sinfo "Listing updates"

    updlist=`mktemp`
    emerge -qupvDN --with-bdeps y --color y @world | tee ${updlist}

    if [ -s ${updlist} ]; then
        echo -n "Press Enter to continue..."
        read
    fi

    rm ${updlist}
fi


sinfo "Compiling world"
emerge -quDN --with-bdeps y @world


# Some news are delayed until first emerge
eselect news read all
eselect news purge


sinfo "Removing unnecessary packages"
emerge -qc --deselect=n


sinfo "Performing package move updates"
emaint -c world
emaint -f moveinst
emaint -f movebin


sinfo "Updating Perl modules"
perl-cleaner --ph-clean --modules -- -q


# sinfo "Updating Python modules"
# python-updater -dmanual -- -q


sinfo "Rebuilding packages that use old libraries"
emerge -q @preserved-rebuild


sinfo "Checking linking consistency"
revdep-rebuild -qi

rm -f ${protected}
etc-update
rebuild_locales


sinfo "Listing GLSAs"
glsa-check -lq


if [ ! -e /var/cache/eix ]; then
    sinfo "Creating eix database"
    eix-update -q
fi


sinfo "Compiling custom executables"
cflags="-std=c99 -Wall -pedantic `portageq envvar CFLAGS` `portageq envvar LDFLAGS`"
gcc  ${cflags} -o /usr/local/sbin/udev-watchdog      /usr/local/src/udev-watchdog.c -ludev
gcc  ${cflags} -o /usr/local/sbin/slay               /usr/local/src/slay.c
gcc  ${cflags} -o /usr/local/sbin/privsh             /usr/local/src/privsh.c
gcc  ${cflags} -o /usr/local/bin/log-limit           /usr/local/src/log-limit.c

cflags="-std=c99 -Wall `portageq envvar CFLAGS`"
mkdir -p /usr/local/addons/initrd
klcc ${cflags} -o /usr/local/addons/initrd/init-kexec /usr/local/src/init-kexec.c

strip -s /usr/local/{sbin/{udev-watchdog,slay,privsh},bin/log-limit} \
         /usr/local/addons/initrd/init-kexec


sinfo "Generating localization, timezone and keyboard layout menus"
${helpdir}/gen-locale-menu


sinfo "Fixing Ambiance/Radiance themes"
sed -ri '/\<(text|icon)-shadow:/ s/([0-9])px\>/\1/g' /usr/share/themes/{Radiance,Ambiance}*/gtk-3.0/{,apps/}*.css


sinfo "Fixing miscellaneous directory permissions"
# (#431920)
chmod go=u-w /var/log/wimax

# (#444734, FreeDesktop: #58787)
chown root:polkitd {/etc,/usr/share}/polkit-1/rules.d
chmod 750          {/etc,/usr/share}/polkit-1/rules.d
chown root:root    {/etc,/usr/share}/polkit-1/rules.d/*
chmod 644          {/etc,/usr/share}/polkit-1/rules.d/*


sinfo "Setting dash as POSIX shell"
eselect sh set dash


# Use RGB sub-pixel rendering (slight degradation on non-RGB LCD / non-DVI cable)
sinfo "Configuring fontconfig"
for fconf in \
    10-sub-pixel-rgb.conf \
    20-unhint-small-dejavu-sans.conf \
    20-unhint-small-dejavu-sans-mono.conf \
    20-unhint-small-dejavu-serif.conf \
    44-wqy-zenhei.conf \
    57-dejavu-sans.conf \
    57-dejavu-sans-mono.conf \
    57-dejavu-serif.conf \
    65-khmer.conf \
    64-ttf-thai-tlwg.conf \
    70-no-bitmaps.conf
do
    if [ ! -f /etc/fonts/conf.d/${fconf} ]; then
        eselect fontconfig enable ${fconf}
    fi
done

# Ghostscript has its urw-fonts dependency stripped
if [ -e /usr/share/fonts/default ]; then
    rm    /usr/share/fonts/default/ghostscript
    rmdir /usr/share/fonts/default
fi


# http://www.x.org/wiki/GalliumStatus
sinfo "Configuring Mesa and OpenGL"
eselect mesa   set --auto
eselect mesa   set i915 classic
eselect mesa   set sw   classic

eselect opengl set xorg-x11


# /usr/local/share/ca-certificates is implicitly trusted
sinfo "Refreshing trusted certificates list"
find -L /etc/ssl/certs -maxdepth 1 -type l -delete
update-ca-certificates -f


sinfo "Generating /etc/issue"
sed "s@VERSION@${LVERSION}@" ${HOME}/config/issue > /etc/issue


sinfo "Patching init scripts"
initpatches="inittab system-auth autofs iptables"
for p in ${initpatches}; do
    spatch ${HOME}/patches/${p}.patch -p0
done
sed -i 's/^# include /include /' /etc/nanorc


sinfo "Configuring start-up services"
svcsysinit="udev"
svcboot="consolefont irqbalance haveged metalog
         iptables consolekit lockdown"
svcdefault="liberte identity cabled persist xconfig vmconfig spindown
            acpid smartd laptop_mode gpm
            autofs NetworkManager privoxy"
svcshutdown="memwipe"
delsvcboot="urandom swap swapfiles bootmisc root mtab"
delsvcdefault="netmount local"
delsvcshutdown="savecache"

for runlevel in sysinit boot default shutdown; do
    eval svcs=\${svc${runlevel}}
    for svc in ${svcs}; do
        [   -e /etc/runlevels/${runlevel}/${svc} ] || rc-update add ${svc} ${runlevel}
    done
done

for runlevel in boot default shutdown; do
    eval svcs=\${delsvc${runlevel}}
    for svc in ${svcs}; do
        [ ! -e /etc/runlevels/${runlevel}/${svc} ] || rc-update del ${svc} ${runlevel}
    done
done

rc-update -u


# /run/lock prevents a dangling symlink
sinfo "Initializing /run"
find /run -mindepth 1 ! -path /run/lock -delete
install -d -g uucp -m 775 /run/lock


# (lastlog is not sparse on overlayfs, wtmp has no growth limit)
# /var/run/utmp is created in bootmisc (which is disabled)
sinfo "Disabling non-rotating logs"
ln -sf /dev/null /var/log/ConsoleKit/history
ln -sf /dev/null /var/log/lastlog
rm -f  /var/log/wtmp


sinfo "Replacing laptop-mode drive-waking hdparm calls"
sed -i 's/`\(hdparm -[SW]\)\>/`fast-\1/' /usr/share/laptop-mode-tools/modules/hdparm


# "wheel"     group: necessary for su/sudo PAM authentication + GRSEC TPE (= 10)
#                    + stop/restart PolicyKit permissions + lid events
# "plugdev"   group: ModemManager control PolicyKit permissions;
#                    + NetworkManager modify system connections
#                    + wireless/bluetooth rfkill switch
# "lp"        group: D-Bus communication with bluetoothd
# ["uucp"]    group: access to RFCOMM devices (e.g., obexftp)
# "games"     group: prevent games complaining about not keeping scores
# "vmware"    group: VMware's drag-n-drop feature for file exchange (when enabled)
# "vboxguest" group: VirtualBox seamless mode, auto-resize and clipboard
sinfo "Setting up users"
sed -i 's/^#\?\(ENCRYPT_METHOD\) .*/\1 SHA256/' /etc/login.defs

pwconv
pwck -qr

grpck -r
grpconv

echo root:liberte | chpasswd
usermod -L root

groupadd -f -r games
groupadd -f -r plugdev
groupadd -g 9000 legion || [ $? = 9 ]
groupadd -g 9001 nofw   || [ $? = 9 ]

useradd -u 2101 -g legion -c "Anonymous"            -d /home/anon                  anon  || [ $? = 9 ]
useradd -u 2102 -g nofw   -c "Non-firewalled"       -d /home/nofw -s /sbin/nologin nofw  || [ $? = 9 ]

# "vmware" disabled (#474636)
usermod -G wheel,plugdev,lp,games,vboxguest anon
usermod -G legion                           cable

useradd -c slay    -d /dev/null -s /sbin/nologin -r slay || [ $? = 9 ]


sinfo "Minimizing SUID bits in favor of POSIX.1e capabilities"
sed -n '/^\//p' ${HOME}/config/rootfs.nosuid | while read file caps; do
    chmod a-s "${file}"
    if [ -n "${caps}" ]; then
        setcap "${caps}" "${file}"
    elif getcap "${file}" | grep -q ^; then
        setcap -r "${file}"
    fi
done


sinfo "Initializing a secondary PGP keyring"
sudo -n -u anon gpg -q --homedir /home/anon/persist/security/pgp --no-default-keyring \
    --keyring liberte.gpg --import /usr/local/addons/certs/liberte-*.asc
install -p -o anon -g legion -m 600 -t /home/anon/persist/security/pgp \
    /usr/local/addons/certs/mfpl.crt

# clear pam_mktemp's append-only attribute to allow later livecd directory removal
chattr -f -a /tmp/.private || :


sinfo "Creating dconf databases"
find /etc/dconf/db -maxdepth 1 -type f -delete
dconf update


# Should be moved before emerge @world once (#447352) is sorted out
sinfo "Generating Secure Boot test certificates"
${helpdir}/gen-sb-cert test


sinfo "Building kernel modules"
${helpdir}/gen-kernel modules


sinfo "Creating initramfs image"
${helpdir}/gen-initramfs


sinfo "Building main and KEXEC kernels"
${helpdir}/gen-kernel


sinfo "Verifying XZ decompression memory requirements"
kernxz=arch/x86/boot/compressed/vmlinux.bin.xz

head -c -4 /usr/src/linux-main/${kernxz}     | xz -t -M $((2 * ${xzmem}))MiB
head -c -4 /usr/src/linux-kexec/${kernxz}    | xz -t -M $((2 * ${xzmem}))MiB
head -c -4 /usr/src/linux-kexec-64/${kernxz} | xz -t -M $((2 * ${xzmem}))MiB

xz -t -M ${xzmem}MiB /usr/src/linux-{main,kexec{,-64}}/usr/initramfs_data.cpio.xz


sinfo "Kernel config differences:"
diff ${HOME}/config/linux-${kversion%-r*}.config          /usr/src/linux-main/.config     || :


sinfo "Kexec kernel config differences:"
diff ${HOME}/config/linux-${kversion%-r*}-kexec.config    /usr/src/linux-kexec/.config    || :
diff ${HOME}/config/linux-${kversion%-r*}-kexec-64.config /usr/src/linux-kexec-64/.config || :


if [ -e /etc/portage/savedconfig/sys-apps/busybox-* ]; then
    sinfo "BusyBox config differences:"
    diff /etc/portage/savedconfig/sys-apps/busybox{,-*} || :
fi


sinfo "Unknown missing firmwares:"
${helpdir}/lst-firmwares


sinfo "Generating SYSLINUX configuration"
${helpdir}/gen-syslinux


sinfo "Generating EFI GRUB configuration"
${helpdir}/gen-efi


sinfo "Done."
