#!/bin/sh

exec 1>/dev/null 2>&1

logger -p 6 -t wicd.scripts "stopping NTP and Tor services"

if [ -e /var/lib/init.d/started/tor ]; then
    /etc/init.d/tor stop
fi

if [ -e /var/lib/init.d/started/ntpd ]; then
    /etc/init.d/ntpd stop
fi
