
$CPAN::Config = {
  'build_cache' => q[100],
  'build_dir' => q[/var/cache/cpan/build],
  'cache_metadata' => q[1],
  'cpan_home' => q[/var/cache/cpan],
  'dontload_hash' => {  },
  'ftp' => q[],
  'ftp_proxy' => q[],
  'getcwd' => q[cwd],
  'gpg' => q[/usr/bin/gpg],
  'gzip' => q[/bin/gzip],
  'histfile' => q[],
  'histsize' => q[100],
  'http_proxy' => q[],
  'inactivity_timeout' => q[0],
  'index_expire' => q[1],
  'inhibit_startup_message' => q[0],
  'keep_source_where' => q[/var/cache/cpan/sources],
  'links' => q[],
  'lynx' => q[],
  'make' => q[/usr/bin/make],
  'make_arg' => q[-j2],
  'make_install_arg' => q[],
  'makepl_arg' => q[PREFIX=/var/tmp/cpan LIB=/var/tmp/cpan/lib],
  'ncftp' => q[],
  'ncftpget' => q[],
  'no_proxy' => q[],
  'pager' => q[less],
  'prerequisites_policy' => q[follow],
  'proxy_user' => q[],
  'scan_cache' => q[atstart],
  'shell' => q[/bin/bash],
  'tar' => q[/bin/tar],
  'term_is_latin' => q[0],
  'unzip' => q[/usr/bin/unzip],
  'urllist' => [q[http://mirrors.ibiblio.org/pub/mirrors/CPAN/], q[http://mirror.switch.ch/ftp/mirror/CPAN/]],
  'wget' => q[/usr/bin/wget],
};
1;
__END__
