#!/bin/sh

sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ -z "$1" ]; then
    echo "$0 <livecd root>"
    exit 1
fi


# Variables
LIVECD=$1/copy
FIND="chroot ${LIVECD} find / -xdev"


sinfo "Checking ${LIVECD}"

sinfo "Bad symlinks:"
${FIND} -type l ! -xtype f ! -xtype d

sinfo "Archives:"
${FIND} \( -name '*.gz' -o -name '*.bz2' -o -name '*.Z' -o -name '*.lzma' \)

sinfo "Sources:"
${FIND} -name '*.h' -o -name '*.inc' -o -name '*.c' -o -name '*.cpp' -o -name '*.m4' -o -name '*.el' -o -name '*.py' -o -name '*.defs' -o -name '*.pl' -o -name '*.pm'

sinfo "Objects:"
${FIND} -name '*.o' -o -name '*.a' -o -name '*.la' -o -name '*.pc'

sinfo "Docs:"
${FIND} -name '*.info' -o -name '*.htm*' -o \( -name '*.1' ! -name '*.so.*' \)

sinfo "Hidden:"
${FIND} -name '.*'

sinfo "Backup:"
${FIND} -name '*~*' -o -name '*-' -o -name '*#*' -o -name '*.bak' -o -name '*;*' -o -name '*.orig'

sinfo "Cache:"
${FIND} -name '*.cache'

sinfo "Logs:"
${FIND} -name '*.log*' -o -type f \( -path '*var/run/*' -o -path '*/var/log/*' \)

sinfo "SUID/SGID:"
${FIND} -type f -perm /u+s -printf '%M %u %g\t%p\n'
${FIND} -type f -perm /g+s -printf '%M %u %g\t%p\n'
${FIND} -type d -perm /a+s -printf '%M %u %g\t%p\n'
