#!/bin/sh

sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ -z "$1" ]; then
    echo "$0 <livecd root>"
    exit 1
fi


# Variables
LIVECD=$1/copy
FIND="chroot ${LIVECD} find / -xdev"


sinfo "Checking ${LIVECD}"

sinfo "Invalid files and symlinks:"
${FIND} ! \( -type d -o -type f -o -type l \
             -o \( -path '/dev/*' -a \( -type c -o -type b \) \) \)
${FIND} -type l ! -xtype f ! -xtype d

sinfo "Archives:"
${FIND} \( -name '*.gz' -o -name '*.bz2' -o -name '*.Z' \
           -o -name '*.lzma' -o -name '*.xz' \)

sinfo "Sources:"
${FIND} -name '*.h' -o -name '*.inc' -o -name '*.c' -o -name '*.cpp' \
        -o -name '*.m4' -o -name '*.el' -o -name '*.py' \
        -o -name '*.defs' -o -name '*.pl' -o -name '*.pm'

sinfo "Objects:"
${FIND} -name '*.o' -o -name '*.a' -o -name '*.la' -o -name '*.pc'

sinfo "Docs:"
${FIND} -name '*.info*' -o -name '*.htm*' -o -name '*.1.bz2'

sinfo "Hidden:"
${FIND} -name '.*' ! \( -path '/home/anon/*' -o -path '/root/*' \)

sinfo "Cache, backup, and temp:"
${FIND} -name '*cache' ! -type d
${FIND} -name '*~*' -o -name '*-' -o -name '*#*' -o -name '*.bak' \
        -o -name '*;*' -o -name '*.orig' -o -path '*/tmp/*'

sinfo "Logs:"
${FIND} -name '*.log*' -o -type f \( -path '/var/run/*' -o -path '/var/log/*' \)

sinfo "SUID/SGID:"
${FIND} -type f -perm /u+s -printf '%M %u %g\t%p\n'
${FIND} -type f -perm /g+s -printf '%M %u %g\t%p\n'
${FIND} -type d -perm /a+s -printf '%M %u %g\t%p\n'
