#!/bin/sh -e

sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ -z "$1" ]; then
    echo "$0 <livecd root> [copy] [-c shell command...]"
    exit 1
fi


# Variables
SRC=`dirname $0`/src

version=`cat ${SRC}/../version`
environment="VERSION=${version} LOGNAME=root USER=root HOME=/root HOSTNAME=liberte"
for env in LANG TERM RSYNC_PROXY http_proxy ftp_proxy; do
    if printenv ${env} 1>/dev/null; then
        environment="${environment} ${env}=`printenv ${env}`"
    fi
done


# Tweak target directory if alternative is given,
# otherwise, synchronize configuration
if [ "$2" = copy ]; then
	LIVECD=$1/$2
    environment="${environment} PHASE=$2"
    shift 2
else
    LIVECD=$1/src
    environment="${environment} PHASE=src"
    shift

    sinfo "Copying configuration files:"
    rsync -aHS -O --no-o --no-g --chmod=go=rX -v --exclude={/root/,/home/anon/,/mnt/hidden/} -C ${SRC}/ ${LIVECD}
    rsync -aHS -O --no-o --no-g --chmod=go=   -v --delete-excluded -C ${SRC}/root       ${LIVECD}
    rsync -aHS -O --no-o --no-g --chmod=go=   -v --delete-excluded -C ${SRC}/mnt/hidden ${LIVECD}/mnt
    # Dirs:  rwx--x---
    # Files: rw-------
    rsync -aHS -O --no-o --no-g --chmod=Dg=x,Fg=,o= -v --delete-excluded -C ${SRC}/home/anon ${LIVECD}/home
fi


sinfo "Mounting system directories"
for dir in proc sys dev dev/pts dev/shm; do
    mount -B /${dir} ${LIVECD}/${dir}
done
if [ -d /usr/portage/distfiles -a -d ${LIVECD}/usr/portage/distfiles ]; then
    mount -B /usr/portage/distfiles ${LIVECD}/usr/portage/distfiles
fi


sinfo "Environment:"
echo "${environment}" | tr ' ' '\n' | sed 's/^/    /'


sinfo "Launching chrooted shell in ${LIVECD}"
env -i ${environment} setarch i686 chroot ${LIVECD} /bin/bash -l "$@" || true


sinfo "Unmounting system directories"
if [ -d /usr/portage/distfiles -a -d ${LIVECD}/usr/portage/distfiles ]; then
    umount ${LIVECD}/usr/portage/distfiles
fi
for dir in dev/shm dev/pts dev sys proc; do
    umount ${LIVECD}/${dir}
done
