#!/bin/sh -e

sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ "$1" = "" ]; then
    echo "$0 <livecd root>"
    exit 1
fi


# Variables
SRC=`realpath $0`
SRC=`dirname ${SRC}`
DIST=$1/dist

version=`grep -o '\<[0-9][0-9][0-9][0-9]\.[0-9]\+\>' ${SRC}/src/etc/issue`
distname=liberte-${version}


sinfo "Building distribution ${distname}"
mkdir -p ${DIST}/${distname}
ln -sf ../liveusb.img  ${DIST}/${distname}/
ln -sf ${SRC}/burn-usb ${DIST}/${distname}/ 

tar -C ${DIST} --owner root --group root -chf ${DIST}/${distname}.tar ${distname}

sinfo "Done."
