#!/bin/sh -e

sinfo() {
    echo -e "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ "$1" = "" ]; then
    echo "$0 <livecd root>"
    exit 1
fi


# Variables
SRC=`realpath $0`
SRC=`dirname ${SRC}`
DIST=$1/dist
# SVN=https://liberte.svn.sourceforge.net/svnroot/liberte/tags

version=`cat ${SRC}/version`
distname=liberte-${version}


if [ "${version}" = "" ]; then
    sinfo "Could not determine distribution version"
    exit 1
fi


sinfo "Building binary distribution ${distname}.zip"
cd ${DIST}
zip -FS -rD9 -q ${distname}.zip liberte


sinfo "Building source distribution ${distname}-src.tar.bz2"
rm -rf ${DIST}/${distname}-src
svn export -q ${SRC} ${DIST}/${distname}-src
chmod -R go=u-w ${DIST}/${distname}-src
tar -C ${DIST} -p --owner root --group root -cjf ${DIST}/${distname}-src.tar.bz2 ${distname}-src
rm -r ${DIST}/${distname}-src


sinfo "Done."
