#!/bin/sh -e

sinfo() {
    echo ${BASH:+-e} "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ -z "$1" ]; then
    echo "$0 <livecd root>"
    exit 1
fi


# Variables
SRC=`dirname $0`
DIST=$1/dist

version=`cat ${SRC}/conf/version`
distname=liberte-${version}


sinfo "Creating source distribution ${distname}-src.tar.bz2"
(cd ${SRC}; git -c tar.umask=022 archive --format=tar --prefix=${distname}/ master) \
    | bzip2 > ${DIST}/${distname}-src.tar.bz2


sinfo "Done."
