#!/bin/sh -e

sinfo() {
    echo ${BASH:+-e} "\033[1;33;41m$@\033[0m"
}


# Must have root directory as an argument
if [ -z "$1" ]; then
    echo "$0 <livecd root>"
    exit 1
fi


# Variables
src=`dirname $0`
livecd=$1/copy
cdroot=$1/dist/cdroot

version=`cat ${src}/conf/version`
distname=liberte-${version}
sysver=`cat ${livecd}/boot/syslinux/version`
mksqver=4.1

luser=2101
lgroup=9000

# see /usr/local/sbin/ps-mount
vfatflags=noatime,noexec,flush,iocharset=iso8859-1,utf8,uid=${luser},gid=${lgroup},umask=0137,dmask=067
isofsflags=nosuid,nodev,iocharset=iso8859-1,utf8,uid=${luser},gid=${lgroup},dmode=0510


# POSIX shells should (probably) support $(())
mibsize() {
    bytes=`stat -c %s "$1"`
    echo $(((bytes + 512 * 1024) / (1024 * 1024)))
}


if type mksquashfs 1>/dev/null 2>&1; then
    mksquashfs=mksquashfs
else
    echo "SquashFS Tools not found"
    exit 1
fi

mksqversion=`${mksquashfs} -version | head -1 | cut -d' ' -f3`
if [ "${mksqversion}" != ${mksqver} ]; then
    echo "Need SquashFS Tools v${mksqver}, but detected v${mksqversion}"
    exit 1
fi


sinfo "Copying USB /boot"
mkdir -p -m 755 ${cdroot} ${cdroot}/liberte ${cdroot}/isolinux
rsync -aHAXS -i --delete-excluded --exclude /boot/syslinux/version \
    ${livecd}/boot ${cdroot}/liberte
sed -i "s/TAG //; s/ROOTFS/vfat/;    s/FSFLAGS/${vfatflags}/"  \
    ${cdroot}/liberte/boot/syslinux/syslinux.cfg

# ISOLINUX doesn't support RockRidge/Joliet, so must replace '-' in filenames
cp -p ${livecd}/boot/syslinux/syslinux.cfg ${cdroot}/liberte/boot/syslinux/isolinux.cfg
sed -i "s/TAG //; s/ROOTFS/iso9660/; s/FSFLAGS/${isofsflags}/;
        s/\(\(FONT\|LINUX\|INITRD\) [^-]*\)-/\1_/" \
    ${cdroot}/liberte/boot/syslinux/isolinux.cfg
cp -p ${cdroot}/liberte/boot/syslinux/isolinux.cfg ${cdroot}/isolinux/isolinux.cfg


sinfo "Copying USB add-ons"
rsync -aHS -i -O --no-o --no-g --chmod=u=rwX,go=rX \
    --delete-excluded -C -f "P /boot/"             \
    ${src}/dist/ ${cdroot}/liberte
sed -i "s/SYSVER/${sysver}/" ${cdroot}/liberte/setup.sh


# Using default block size of 128KiB
# Multi-threaded execution often causes deadlock after image creation
sinfo "Creating SquashFS image"

${mksquashfs} ${livecd} ${cdroot}/liberte/boot/root-x86.sfs  \
    -noappend -no-exports -no-progress -no-xattrs -comp lzma \
    -sort ${src}/conf/rootfs.sort -e boot tmp/packages
chmod 644 ${cdroot}/liberte/boot/root-x86.sfs


sinfo "Converting text files to DOS line endings"
find ${cdroot} \( -name '*.txt' -o -name '*.bat' -o -name '*.cfg' \) \
    -exec sed -i 's/$/\r/' {} \;


sinfo "Building binary distribution ${distname}.zip"
zipfile=${cdroot}/../${distname}.zip
(cd ${cdroot}; zip -FS -r9 -q ${zipfile} liberte)


# Hide root directories on Windows, and reset volume information
sinfo "Creating ISO image ${distname}.iso"
isofile=${cdroot}/../${distname}.iso
mkisofs -quiet -iso-level 2 -no-pad -J -sysid '' -V '' -A '' \
    -r -dir-mode 0510 -new-dir-mode 0510                     \
    -no-emul-boot -boot-load-size 4 -boot-info-table         \
    -c boot.cat -hide boot.cat -hide-joliet boot.cat         \
    -b liberte/boot/syslinux/isolinux.bin -o ${isofile}      \
    -hidden isolinux -hidden liberte -hide-joliet isolinux -hide-joliet liberte ${cdroot}
isovfy ${isofile}


echo "Disk usage: `du -s --apparent-size -B 1M ${cdroot} | cut -f1` MiB"
echo "ZIP size:   `mibsize ${zipfile}` MiB"
echo "ISO size:   `mibsize ${isofile}` MiB"


sinfo "Done."
