#!/bin/sh

exec 1>/dev/null 2>&1

iface=$1
action=$2

case ${action} in
*up)
        # htpdate doesn't bind itself to interfaces, it resolves
        # hostnames every time it sends a HEAD request.
        # The custom version sets the time once the network
        # is available, and uses adjtime afterwards.
        if ! /etc/init.d/htpdate -q status; then
            logger -p 6 -t nm.dispatch "Starting HTP service (${iface})"
            /etc/init.d/htpdate -q start
        fi
        ;;
esac
