#!/bin/sh

exec 1>/dev/null 2>&1

iface=$1
action=$2

case ${action} in
*up)
        # htpdate doesn't bind itself to interfaces, it resolves
        # hostnames every time it sends a HEAD request
        if [ ! -e /var/lib/init.d/started/htpdate ]; then
            logger -p 6 -t nm.dispatch "Starting HTP service (${iface})"
            /etc/init.d/htpdate start
        # However, htpdate can be started when there is no connection to
        # the sites; time difference might be too big for adjtime then
        else
            logger -p 6 -t nm.dispatch "Restarting HTP service (${iface})"
            /etc/init.d/htpdate restart
        fi
        ;;
esac
