#!/bin/sh

exec 1>/dev/null 2>&1

iface=$1
action=$2

case ${action} in
*up)
        # tlsdated doesn't bind itself to interfaces
        if ! /etc/init.d/tlsdated -q status; then
            logger -p 6 -t nm.dispatch "Starting tlsdated service (${iface})"
            /etc/init.d/tlsdated -qS start
        fi
        ;;
esac
