#!/bin/sh

exec 1>/dev/null 2>&1

iface=$1
action=$2

case ${action} in
*up|vpn-down)
        if ! /etc/init.d/tor -q status; then
            logger -p 6 -t nm.dispatch "Starting Tor service (${iface})"
            /etc/init.d/tor -q start
        else
            # SIGHUP doesn't refresh sockets, and Tor doesn't handle
            # changing IPs/interfaces well
            logger -p 6 -t nm.dispatch "Restarting Tor service (${iface})"
            /etc/init.d/tor -q restart
        fi
        ;;
esac
