#!/bin/sh

exec 1>/dev/null 2>&1

iface=$1
action=$2

case ${action} in
*up)
        if [ ! -e /var/lib/init.d/started/tor ]; then
            logger -p 6 -t nm.dispatch "Starting Tor service (${iface})"
            /etc/init.d/tor start --quiet
            tor-date &
        else
            # SIGHUP doesn't refresh sockets, and Tor doesn't handle
            # changing IPs/interfaces well
            logger -p 6 -t nm.dispatch "Restarting Tor service (${iface})"
            /etc/init.d/tor restart --quiet
            tor-date &
        fi
        ;;
esac
