#!/bin/sh

exec 1>/dev/null 2>&1

iface=$1
action=$2

case ${action} in
*up|vpn-down)
        # I2P isn't very good with changing IPs/interfaces.
        if ! /etc/init.d/i2p -q status; then
            logger -p 6 -t nm.dispatch "Starting I2P service (${iface})"
            /etc/init.d/i2p -q start
        else
            logger -p 6 -t nm.dispatch "Restarting I2P service (${iface})"
            /etc/init.d/i2p -qs restart
        fi
        ;;

down)
        # I2P hogs the CPU when it is unable to connect to peers
        # NOTE: might be problematic with 2+ NICs
        if /etc/init.d/i2p -q status; then
            logger -p 6 -t nm.dispatch "Stopping I2P service (${iface})"
            /etc/init.d/i2p -qs stop
        fi
        ;;
esac
