#!/bin/sh -e

# C sort ordering matters for "-" extension entries
export LC_ALL=C


# Paths
live=/mnt/live
paklist=${live}/boot/packages.lst

pakdir=${live}/tmp/transient/pkg
unlisted=${pakdir}/unlisted-files

sqsort=${pakdir}/squashfs.sort


echo "Creating pruned packages list"
pakdir=${live}/tmp/transient/pkg
for p in ${pakdir}/*=*; do
    sort ${p} | while read f; do
        if [ -h ${live}"${f}"  -o  -e ${live}"${f}" ]; then
            echo "${f}" >> ${p}.pruned
        fi
    done

    if [ -e ${p}.pruned ]; then
        mv ${p}.pruned ${p}
    else
        rm ${p}
    fi
done

find ${pakdir} -type f -name '*=*' -printf '%f\n' \
    | tr = / | sort > ${paklist}

    # Skip files with spaces to prevents problems with SquashFS sorting
echo "Creating unregistered files list"
find ${live} -xdev \( -type l -o -type f \) ! -name '* *' \
    ! -path "${pakdir}/*" ! -path "${live}/boot/*"        \
    ! -path "${live}/dev/*" -printf '/%P\n' | sort        \
    > ${pakdir}/all-files
sort -u -o ${pakdir}/listed-files ${pakdir}/*=*

comm -13  ${pakdir}/listed-files ${pakdir}/all-files > ${unlisted}
rm        ${pakdir}/listed-files ${pakdir}/all-files


# Order on <mimetype,extension,package,directory>
# Unreferenced files have default priority 0 (which is the top priority)
priority=0
last=

# Some files have : in name, but none have space (filtered previously)
echo "Creating SquashFS ordering"
for p in ${unlisted} ${pakdir}/*=*; do
    sed "s:^:${live}:" ${p}                \
        | file -zhN --mime-type -F '' -f - \
        | while read file mimetype; do
              ext="${file##*.}"
              [ "${file}" != "${ext}" ] || ext=-

              #    <mimetype>    <extension> <package>  <directory>  <live-prefix + file>
              echo "${mimetype}" "${ext}"    "${p##*/}" "${file%/*}" "${file}"
          done
done \
    | sort -s -k1,4 \
    | while read key1 key2 key3 key4 file; do
          # priority per each file would be too wasteful (-32768..32767)
          if [ "${key1} ${key2} ${key3} ${key4}" != "${last}" ]; then
              priority=$((priority-1))
              last="${key1} ${key2} ${key3} ${key4}"
          fi

          echo "${file#${live}/}" ${priority}
      done \
    > ${sqsort}
