#!/bin/sh -e

export LC_ALL=C


# Fetch URL and parameters
netdburl=https://euve5653.vserver.de/netDb/

maxnetdblst=2000
maxfetches=5
maxnetdb=100


# Regular expressions (extended)
rinfore='routerInfo-[[:alnum:]~-]{43}=\.dat'


# Paths
netdbdir=/tmp/netDb
netdblst=${netdbdir}/names
netdberr=${netdbdir}/errors
i2pjar=/opt/i2p/lib/i2p.jar


# Retrieve >= maxnetdblst routerInfos (in overlapping portions of 100)
# in at most maxfetches attempts (hard limit)
rm -rf ${netdbdir}
mkdir  ${netdbdir}
touch  ${netdblst}
while [ "`cat ${netdblst} | wc -l`" -lt ${maxnetdblst}    \
            -a  ${maxfetches} -gt 0 ]; do
    # curl error code is discarded in pipe
    curl -k -sfg --compressed ${netdburl}                 \
        | sed 's/>/>\n/g'                                 \
        | sed -nr "s@^.*\<href=\"(${rinfore})\".*\$@\1@p" \
        >> ${netdblst}

    # remove added duplicate entries
    sort -u ${netdblst} > ${netdblst}.tmp
    mv ${netdblst}.tmp ${netdblst}

    maxfetches=$((maxfetches - 1))
done

# Pick arbitrary maxnetdblst entries
shuf -n ${maxnetdblst} -o ${netdblst}.tmp ${netdblst}
mv ${netdblst}.tmp ${netdblst}


if [ ! -s ${netdblst} ]; then
    rm -r ${netdbdir}
    exit 1
else
    echo "Retrieving `cat ${netdblst} | wc -l` routerInfos"
    curl -k -s --compressed -o ${netdbdir}/#1 \
        ${netdburl}`cat ${netdblst} | tr '\n' , | sed 's/^/{/; s/,$/}/'` || :

    # Delete non-conforming files as precautionary measure (includes namedblst)
    find ${netdbdir} -regextype posix-egrep -mindepth 1 \
        \( ! -type f -o ! -regex "${netdbdir}/${rinfore}" \) -delete

    # Delete fetch errors
    rm -f `file -N --mime-type -F '' ${netdbdir}/routerInfo-*=.dat | sed -n 's/ text\/html$//p'`

    # Make sure all files are in correct format
    java -cp ${i2pjar} net.i2p.data.RouterInfo ${netdbdir}/routerInfo-*=.dat 1>/dev/null 2>${netdberr}
    if [ -s ${netdberr} ]; then
        echo "Error parsing fetched routerInfos"
        exit 1
    fi
    rm ${netdberr}

    # Delete non-NTCP+OR/OfR-capable routerInfos
    # (see http://zzz.i2p.to/topics/280)
    java -cp ${i2pjar} net.i2p.data.RouterInfo ${netdbdir}/routerInfo-*=.dat \
        | sed -nr 's/^[[:blank:]]+//; /^(Hash: [[:alnum:]~-]{43}=|TransportStyle: NTCP|\[caps\] = \[(OR|OfR)\])$/p' \
        | tr '\n' ,                                                  \
        | sed -r 's/,(Hash:|$)/\n\1/g'                               \
        | sed -r '/,TransportStyle:.*,\[caps\]/d'                    \
        | sed -r "s@^Hash: ([^,]*).*@${netdbdir}/routerInfo-\1.dat@" \
        | xargs rm -f --

    # Delete arbitrary extraneous routerInfos
    netdborig=`find ${netdbdir} -type f | wc -l`
    find ${netdbdir} -type f | shuf | tail -n +$((maxnetdb+1)) | xargs rm -f --

    netdbsel=`find ${netdbdir} -type f | wc -l`
    echo "Selected ${netdbsel} (out of ${netdborig}) NTCP+OR/OfR-capable routerInfos"
fi
