#!/bin/sh -e

# sys-kernel/linux-firmware sublist
fwlst=/etc/portage/savedconfig/sys-kernel/linux-firmware


# serial_cs:          necessary firmware included by kernel automatically
# b43, b43legacy:     net-wireless/b43-firmware
# atmel,at76c50x-usb: net-wireless/atmel-firmware
for fw in $(strings -a -n 10                               \
              $(find /lib/modules -name '*.ko'             \
                                  ! -name serial_cs.ko     \
                                  ! -name b43.ko           \
                                  ! -name b43legacy.ko     \
                                  ! -name atmel.ko         \
                                  ! -name at76c50x-usb.ko) \
              | sed -n 's/^firmware=//p'                   \
              | sort -u); do
    if [ ! -e /lib/firmware/${fw} ] && ! grep -q "^${fw}\$" ${fwlst}; then
        echo ${fw}
    fi
done
