#!/bin/bash -e

# sys-kernel/linux-firmware sublist
fwlst=/etc/portage/savedconfig/sys-kernel/linux-firmware

# initramfs image
initrd=/usr/src/linux-main/usr/initramfs_data.cpio.xz

# Kernel version
hsversion=`cat ${HOME}/config/kversion`
kversion=${hsversion/-/-hardened-}
[ ${kversion} != ${hsversion} ] || kversion=${hsversion}-hardened


# Firmware requested by kernel modules
fwfiles=$(modinfo -k ${kversion} -F firmware \
    $(find /lib/modules -name '*.ko' -printf '%f\n' | sed 's/\.ko$//') \
    | sort -u)

for fw in ${fwfiles}; do
    if [ ! -e /lib/firmware/${fw} ] && ! grep -q "^${fw}\$" ${fwlst}; then
        # atmel, at76c50x-usb: sys-firmware/atmel-firmware
        if [[ !(${fw} =~ atmel_at76c50[45].*\.bin) ]]; then
            echo ${fw}
        fi
    fi
done


# Check for unneeded linux-firmware entries
echo ${fwfiles} | tr ' ' '\n'                         \
    | comm -13 - <(sed -n '/^[^#]/p' ${fwlst} | sort) \
    | sed '/^brcm\/bcm43xx/d; /^v4l-/d'               \
    | sed 's/^/unneeded: /'


# Ensure that initramfs modules do not require any firmware
strings -a -n 10 $(bsdtar tf ${initrd} 'lib/modules/*.ko' | sed 's:^:/:') \
    | sed -n 's/^firmware=//p' | sort -u                                  \
    | sed 's/^/initramfs: /'
