#!/bin/bash -e

# sys-kernel/linux-firmware sublist
fwlst=/etc/portage/savedconfig/sys-kernel/linux-firmware

# initramfs image
initrd=/usr/src/linux-main/usr/initramfs_data.cpio.xz


# b43, b43legacy:     net-wireless/b43[legacy]-firmware
# atmel,at76c50x-usb: net-wireless/atmel-firmware
for fw in $(strings -a -n 10                                   \
              $(find /lib/modules -name '*.ko'                 \
                     ! -name b43.ko   ! -name b43legacy.ko     \
                     ! -name atmel.ko ! -name at76c50x-usb.ko) \
              | sed -n 's/^firmware=//p' | sort -u); do
    if [ ! -e /lib/firmware/${fw} ] && ! grep -q "^${fw}\$" ${fwlst}; then
        echo ${fw}
    fi
done


# Check for unneeded linux-firmware entries
strings -a -n 10 $(find /lib/modules -name '*.ko')    \
    | sed -n 's/^firmware=//p' | sort -u              \
    | comm -13 - <(sed -n '/^[^#]/p' ${fwlst} | sort) \
    | sed '/^brcm\/bcm43xx/d; /^v4l-/d'               \
    | sed 's/^/unneeded: /'


# Ensure that initramfs modules do not require any firmware
strings -a -n 10 $(bsdtar tf ${initrd} 'lib/modules/*.ko' | sed 's:^:/:') \
    | sed -n 's/^firmware=//p' | sort -u                                  \
    | sed 's/^/initramfs: /'
