#!/bin/sh -e

# Variables
cdroot=/mnt/boot/cdroot
live=/mnt/live

ziimage=${cdroot}/liberte/boot/kernel-x86.zi
sqimage=${cdroot}/liberte/boot/root-x86.sfs

efisbpfx=/usr/local/addons/secureboot/Liberte-SecureBoot

sysver=`syslinux -v 2>&1 | cut -d' ' -f2`


echo "Initializing /liberte"

rsync -aHS ${HOME}/dist/                        ${cdroot}/liberte
rsync -aHS ${live}/boot     --exclude /boot/EFI ${cdroot}/liberte
rsync -aHS ${live}/boot/EFI                     ${cdroot}

sed -i "s/SYSVER/${sysver}/"                    ${cdroot}/liberte/setup.sh

find ${cdroot}/liberte \( -name '*.txt' -o -name '*.bat' -o -name '*.cfg' \) \
    -exec sed -i 's/$/\r/' {} \;


echo "Adapting Syslinux and GRUB configuration"

fshash=`sha256sum ${sqimage}`
sed -i "s/FSHASH/${fshash%% *}/"                  \
    ${cdroot}/liberte/boot/syslinux/syslinux.cfg  \
    ${cdroot}/liberte/boot/grub/grub.cfg          \
    ${cdroot}/liberte/qemulate.sh

sha256sum ${cdroot}/liberte/boot/grub/* ${ziimage}  \
    | sed "/\<grub\.\(cfg\|mf\)\>/d; s:${cdroot}::" \
    > ${cdroot}/liberte/boot/grub/grub.mf

grub1hash=`sha256sum ${cdroot}/liberte/boot/grub/grub.cfg`
grub2hash=`sha256sum ${cdroot}/liberte/boot/grub/grub.mf`
sed -i "s/replace_hash_\{50\}01/${grub1hash%% *}/ ; \
        s/replace_hash_\{50\}02/${grub2hash%% *}/"  \
    ${cdroot}/EFI/BOOT/*.EFI


echo "Signing EFI GRUB images"

cp -p ${efisbpfx}-CA.der ${cdroot}/EFI/
for efiimg in ${cdroot}/EFI/BOOT/*.EFI; do
    sbsign   --cert ${efisbpfx}-Cert-1.crt --key ${efisbpfx}-Cert-1.key \
             --output ${efiimg}.signed ${efiimg}
    sbverify --cert ${efisbpfx}-CA.crt ${efiimg}.signed
    mv ${efiimg}.signed ${efiimg}
done
