#!/bin/sh -e

export LC_ALL=C


# Regular expressions (extended)
i2phosts_regexp='^[[:alnum:].-]{1,63}.i2p=[[:alnum:]~-]{512}AAAA[[:blank:]]?$'


# Paths
drivedb=/usr/share/smartmontools/drivedb.h
tmpdb=/tmp/drivedb.h

i2phosts=/opt/i2p/hosts.txt


# Verify SMART database (also, given directly to smartctl during update)
cpp -x c -fpreprocessed -std=c99 -nostdinc -undef -Wall -Werror -pedantic-errors \
    -o ${tmpdb} ${drivedb}
drivedbout=$(sed '/^ *$/d; /^#/d; s/ //g; s/\\"//g; s/"[^"]*"//g' ${tmpdb} \
                 | tr -d '\n' | sed 's/{,,,,},//g' | wc -c)

if [ "${drivedbout}" != 0 ]; then
    echo "${drivedb} verification failed"
    exit 1
fi

rm ${tmpdb}


# Verify I2P hosts
awk --posix "! /${i2phosts_regexp}/ { print; exit 1 }" ${i2phosts}
