#!/bin/sh -e

# Character classes in regexps
export LC_ALL=C

# SERVERS contains list of HTP servers
. /etc/conf.d/htpdate

# Time discrepancy tolerance and connection retries per server
maxdiff=60
retries=3

# RFC 1123 Date: header regexp
# http://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.3.1
datere='[[:alpha:]]{3}, [[:digit:]]{2} [[:alpha:]]{3} [[:digit:]]{4} [[:digit:]:]{8} GMT'


# Gather timestamps in seconds-since-epoch format
htpdates=
for htp in ${SERVERS}; do
    echo -ne "${htp}:\t"

    # Try to get the header several times (-f skips proxy headers)
    htpdate=
    count=${retries}
    while [ -z "${htpdate}"  -a  ${count} -ne 0 ]; do
        htpdate=`curl -sfI ${htp} | sed -rn "s/^Date: (${datere})\r\$/\1/p"`
        count=$((count - 1))
    done

    # Fail if unsuccessful
    if [ -z "${htpdate}" ]; then
        echo "failed after ${retries} attempts"
        exit 1
    fi


    # Add seconds-since-epoch timestamp
    echo "${htpdate}"
    htpdates="${htpdates} "`date +%s -ud "${htpdate}"`
done


htpmin=`echo ${htpdates} | tr ' ' '\n' | sort -n | head -n 1`
htpmax=`echo ${htpdates} | tr ' ' '\n' | sort -n | tail -n 1`

if [ $((htpmax - htpmin)) -gt ${maxdiff} ]; then
    echo "HTP servers disagreement > ${maxdiff}s"
    exit 1
fi
