#!/bin/sh -e

export LC_ALL=C


# Regular expressions (extended)
pciids_regexp='^([[:xdigit:]]{4}|\t(\t[[:xdigit:]]{4} )?[[:xdigit:]]{4}|(C |\t\t?)[[:xdigit:]]{2})  [^[:cntrl:]]{0,320}$|^#[[:blank:][:graph:]]{0,320}$|^$'
usbids_regexp='^((AT|HID|R|BIAS|PHY|HUT|L|HCC|VT) |\t)[[:xdigit:]]{1,4}  [^[:cntrl:]]{0,320}$'
i2phosts_regexp='^[[:alnum:].-]{1,63}.i2p=[[:alnum:]~-]{512}AAAA[[:blank:]]?$'


# Paths
pciids=/usr/share/misc/pci.ids
usbids=/usr/share/misc/usb.ids

drivedb=/usr/share/smartmontools/drivedb.h
tmpdb=/tmp/drivedb.h

i2phosts=/opt/i2p/hosts.txt


# Verify PCI/USB IDs
awk --posix "! /${pciids_regexp}/                  { print; exit 1 }" ${pciids}
awk --posix "! /${pciids_regexp}|${usbids_regexp}/ { print; exit 1 }" ${usbids}


# Verify SMART database (also, given directly to smartctl during update)
cpp -x c -fpreprocessed -std=c99 -nostdinc -undef -Wall -Werror -pedantic-errors \
    -o ${tmpdb} ${drivedb}
drivedbout=$(sed '/^ *$/d; /^#/d; s/ //g; s/\\"//g; s/"[^"]*"//g' ${tmpdb} \
                 | tr -d '\n' | sed 's/{,,,,},//g' | wc -c)

if [ "${drivedbout}" != 0 ]; then
    echo "${drivedb} verification failed"
    exit 1
fi

rm ${tmpdb}


# Verify I2P hosts
awk --posix "! /${i2phosts_regexp}/ { print; exit 1 }" ${i2phosts}
