#!/bin/sh -e

if [ "$1" = fork ]; then
    nginxflag=/var/lib/init.d/started/nginx
    pidfile=/var/run/cabled.pid

    if [ ! -e ${nginxflag} ]; then
        :
    fi

    sudo -n -u "${CHUSER}" -s /bin/sh -c "$0"' & echo $!' > ${pidfile}
    exit
fi

. /usr/local/libexec/suexec/suprofile


# Variables
cableexec=`dirname $0`


sleep 999999
