#!/bin/sh -e

# Setup environment with needed environment vars
. "${0%"${0##*/}"}"suprofile


# Command-line parameters
if [ $# != 1 ]; then
    echo "Format: $0 user@host"
    exit 1
fi


error() {
    echo "cable-ping: $@" 1>&2
    exit 1
}


emailregex="${CABLE_REGEX}"
cableregex="LIBERTE CABLE [[:alnum:]._-]+"
maxresp=128
addr="$1"

if ! echo x "${addr}" | egrep -q "^x ${emailregex}$"; then
    error "unsupported address"
fi


user=`echo "${addr}" | cut -d@ -f1`
host=`echo "${addr}" | cut -d@ -f2`
url=http://"${host}"/"${user}"/request/ver


# Pipe eats curl's error status, if any
resp=`curl -sSfg "${url}" 2>&1 | head -c ${maxresp} | tr -cd '[:alnum:][:blank:]:()._-'`

if echo x "${resp}" | grep -q "^x curl:"; then
    error "communication error: ${resp}"
elif echo x "${resp}" | egrep -q "^x ${cableregex}$"; then
    echo "${resp}"
else
    error "unexpected output: ${resp}"
fi
