#!/bin/sh -e

# Setup environment with needed environment vars
. "${0%"${0##*/}"}"suprofile


error() {
    echo "cable-id: $@" 1>&2
    exit 1
}

torhost=${CABLE_TOR}/hidden_service/hostname
i2phost=${CABLE_I2P}/eepsite/hostname
username=${CABLE_CERTS}/certs/username


if [ ! -e ${torhost} ]; then
    error "Tor host identity not initialized yet"
fi

if [ ! -e ${i2phost} ]; then
    error "I2P host identity not initialized yet"
fi

if [ ! -e ${username} ]; then
    error "cable identity not initialized yet"
fi


torhost=`cat ${torhost} | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
i2phost=`cat ${i2phost} | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
username=`cat ${username} | tr -cd a-z2-7`

[ ${#torhost} != 0 ]  || error "bad Tor hostname"
[ ${#i2phost} != 0 ]  || error "bad I2P hostname"
[ ${#username} = 32 ] || error "bad username"


case "$1" in
    tor)
        echo "${username}"@"${torhost}"
        ;;

    i2p)
        echo "${username}"@"${i2phost}"
        ;;

    test)
        echo http://"${torhost}"/"${username}"/request/ver
        echo http://"${i2phost}"/"${username}"/request/ver
        ;;

    *)
        error "param: tor|i2p|test"
        ;;
esac
