#!/bin/sh -e

# Encryption, decryption and verification of messages and message receipts
# NOTE: the "-e" switch above is important (script failure on error)!

umask 077
export LC_ALL=C


# Variables
cmd="$1"
ssldir="$2"
msgdir="$3"

sigalg=sha512
encalg=aes256

base32=hex2base32


# Command-line parameters
if [ \( "${cmd}" != send -a "${cmd}" != recv -a "${cmd}" != ack \) \
     -o  ! -d "${ssldir}"  -o  ! -d "${msgdir}" ]; then
    echo "Format: $0 send|recv|ack <ssldir> <msgdir>"
    exit 1
fi


error() {
    echo "cms (${msgdir##*/}): $1" 1>&2
    exit 1
}


# Verifying the ca/verify/encrypt certificates triple
# * parses and extracts the first certificate from each file
# * verifies the certificates chain (important only for encrypt.pem)
# * generates username from ca.pem and checks it against the given one
verify_certs() {
    local cvedir="$1" name count fingerprint

    for name in ca verify encrypt; do
        openssl x509 -in  "${cvedir}"/${name}.pem \
                     -out "${cvedir}"/${name}.norm.pem
        mv -- "${cvedir}"/${name}.norm.pem "${cvedir}"/${name}.pem

        # Sanity check - OpenSSL should output exactly 1 certificate
        count=`sed -n '/^-----BEGIN /p' -- "${cvedir}"/${name}.pem | wc -l`
        [ "${count}" = 1 ]
    done

    openssl verify -x509_strict -policy_check -purpose crlsign -check_ss_sig \
        -CApath /dev/null -CAfile "${cvedir}"/ca.pem "${cvedir}"/ca.pem \
        >  "${cvedir}"/certs.vfy 2>&1
    openssl verify -x509_strict -policy_check -purpose smimesign \
        -CApath /dev/null -CAfile "${cvedir}"/ca.pem "${cvedir}"/verify.pem \
        >> "${cvedir}"/certs.vfy 2>&1
    openssl verify -x509_strict -policy_check -purpose smimeencrypt \
        -CApath /dev/null -CAfile "${cvedir}"/ca.pem "${cvedir}"/encrypt.pem \
        >> "${cvedir}"/certs.vfy 2>&1

    cat > "${cvedir}"/certs.cmp <<EOF
${cvedir}/ca.pem: OK
${cvedir}/verify.pem: OK
${cvedir}/encrypt.pem: OK
EOF

    if ! cmp -s -- "${cvedir}"/certs.vfy "${cvedir}"/certs.cmp; then
        error "certificates chain verification failed"
    fi

    rm -- "${cvedir}"/certs.cmp "${cvedir}"/certs.vfy


    openssl x509 -in "${cvedir}"/ca.pem -outform der -out /dev/null
    fingerprint=`openssl x509 -in "${cvedir}"/ca.pem -outform der | sha1sum | head -c 40`
    [ ${#fingerprint} = 40 ]
    ${base32} "${fingerprint}" > "${cvedir}"/username.cmp

    if ! cmp -s -- "${cvedir}"/username "${cvedir}"/username.cmp; then
        error "username verification failed"
    fi

    rm -- "${cvedir}"/username.cmp
}


# Public certificates and private keys in PEM format
# ${certdir}/ca.pem      : X.509 self-signed root CA certificate
# ${certdir}/verify.pem  : X.509 signature verification certificate (issued by root CA)
# ${certdir}/encrypt.pem : X.509 encryption certificate             (issued by root CA)
# ${keysdir}/sign.pem    : private signature key
# ${keysdir}/decrypt.pem : private decryption key (may be the same as signature key)
certdir="${ssldir}"/certs
keysdir="${ssldir}"/private


# Input and output files are in ${msgdir}
#
# (all)
#     in:  ca.pem, verify.pem, encrypt.pem
#
# <send>
#     in:  message, username
#     out: message.sig, message.out
#
# ---> message.out
#
# <recv>
#     in:  message.out, username
#     out: message, receipt.{ack,out}
#
# <--- receipt.out
#
# <ack> (expects <send>'s directory)
#     in:  receipt.out, message.sig
#     out: receipt.ack

case ${cmd} in
send)
    rm -f -- "${msgdir}"/message.sig "${msgdir}"/message.out \
             "${msgdir}"/receipt.sig "${msgdir}"/receipt.ack "${msgdir}"/receipt.out

    verify_certs "${msgdir}"

    # NOTE: -noattr is partially ignored
    openssl cms -sign -noattr -binary -md ${sigalg} -nodetach \
                -receipt_request_all -receipt_request_to auto \
                -outform der -nocerts                 \
                -signer   "${certdir}"/verify.pem     \
                -inkey    "${keysdir}"/sign.pem       \
                -in       "${msgdir}"/message         \
                -out      "${msgdir}"/message.sig

    openssl cms -encrypt -binary -${encalg} -outform pem \
                -in       "${msgdir}"/message.sig \
                -out      "${msgdir}"/message.out \
                          "${msgdir}"/encrypt.pem
    ;;


recv)
    rm -f -- "${msgdir}"/message.sig "${msgdir}"/message    \
             "${msgdir}"/receipt.sig "${msgdir}"/receipt.ack "${msgdir}"/receipt.out

    verify_certs "${msgdir}"

    openssl cms -decrypt -inform pem \
                -recip    "${certdir}"/encrypt.pem \
                -inkey    "${keysdir}"/decrypt.pem \
                -in       "${msgdir}"/message.out  \
                -out      "${msgdir}"/message.sig

    openssl cms -verify -inform der \
                -x509_strict -policy_check -purpose smimesign -check_ss_sig \
                -CAfile   "${msgdir}"/ca.pem -CApath /dev/null \
                -certfile "${msgdir}"/verify.pem  \
                -in       "${msgdir}"/message.sig \
                -out      "${msgdir}"/message

    # NOTE: -md (and partially, -noattr) are ignored
    openssl cms -sign_receipt -noattr -md ${sigalg} -nodetach \
                -inform der -outform der -nocerts \
                -signer   "${certdir}"/verify.pem \
                -inkey    "${keysdir}"/sign.pem   \
                -in       "${msgdir}"/message.sig \
                -out      "${msgdir}"/receipt.sig

    openssl cms -encrypt -binary -${encalg} -outform pem \
                -in       "${msgdir}"/receipt.sig \
                -out      "${msgdir}"/receipt.out \
                          "${msgdir}"/encrypt.pem

    ${sigalg}sum -- "${msgdir}"/receipt.sig | sed 's/[[:blank:]].*//' \
                 >  "${msgdir}"/receipt.ack
    [ -s "${msgdir}"/receipt.ack ]

    rm -- "${msgdir}"/message.sig "${msgdir}"/receipt.sig
    ;;


ack)
    rm -f -- "${msgdir}"/receipt.sig "${msgdir}"/receipt.ack

    openssl cms -decrypt -inform pem \
                -recip    "${certdir}"/encrypt.pem \
                -inkey    "${keysdir}"/decrypt.pem \
                -in       "${msgdir}"/receipt.out  \
                -out      "${msgdir}"/receipt.sig

    openssl cms -x509_strict -policy_check -purpose smimesign -check_ss_sig \
                -inform der -rctform der \
                -CAfile         "${msgdir}"/ca.pem -CApath /dev/null \
                -certfile       "${msgdir}"/verify.pem  \
                -verify_receipt "${msgdir}"/receipt.sig \
                -in             "${msgdir}"/message.sig

    ${sigalg}sum -- "${msgdir}"/receipt.sig | sed 's/[[:blank:]].*//' \
                 >  "${msgdir}"/receipt.ack
    [ -s "${msgdir}"/receipt.ack ]

    rm -- "${msgdir}"/receipt.sig
    ;;


*)
    error "unknown command"
    ;;
esac
