#!/bin/sh -e

umask 077
export LC_ALL=C


if [ $# != 2 ]; then
    echo "Format: $0 send|recv|ack|fin <msgid>"
    exit 1
fi


# Directories and files
username=`cat ${SECURITY_HOME}/ssl/certs/username | tr -cd a-z2-7`
queue=${HOME}/persist/cables/queue
rqueue=${HOME}/persist/cables/rqueue
pubqueue=/var/www/"${username}"/queue
pubrqueue=/var/www/"${username}"/rqueue

# Parameters
cmd="$1"
msgid="$2"


error() {
    echo "comm: $1" 1>&2
    exit 1
}


urlprefix() {
    local username=`cat $1/"${msgid}"/username | tr -cd a-z2-7`
    local hostname=`cat $1/"${msgid}"/hostname | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
    check_userhost "${username}" "${hostname}"

    echo http://"${hostname}"/"${username}"/request
}


# Atomic no-clobber copy
atomicnccopy() {
    local src="$1" dst="$2"

    if [ ! -e "${dst}" ]; then
        # prevent race condition in possible implementations of max retry-num
        if cp -T "${src}" "${dst}".new && [ -e "${src}" ]; then
            chmod 640 "${dst}".new
            mv -T "${dst}".new "${dst}"
        else
            rm -f "${dst}".new
            error "failed to copy ${src}"
        fi
    fi
}


# Sanity checks
[ ${#msgid}    = 40 ] || error "bad msgid"
[ ${#username} = 32 ] || error "bad own username"
[ -e "${pubqueue}"  ] || error "public queue does not exist"
[ -e "${pubrqueue}" ] || error "public rqueue does not exist"

check_userhost() {
    [ ${#1} = 32 ] || error "bad username"
    [ ${#2} != 0 ] || error "bad hostname"
}


case "${cmd}" in
send)
    # <send> [comm loop]
    if [ -e ${queue}/"${msgid}"/${cmd}.ok     \
         -a   ! -e ${queue}/"${msgid}"/ack.ok ]; then
        prefix=`urlprefix ${queue}`

        shostname=`cat ${queue}/"${msgid}"/shostname | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
        check_userhost "${username}" "${shostname}"

        atomicnccopy ${queue}/"${msgid}"/message.out "${pubqueue}"/"${msgid}"
        curl -sSfg -o ${queue}/"${msgid}"/${cmd}.ans \
                   "${prefix}"/msg/"${msgid}"/"${shostname}"/"${username}"
    else
        error "${cmd}.ok (without ack.ok) not found"
    fi
    ;;

recv)
    # <recv> [comm loop]
    if [ -e ${rqueue}/"${msgid}"/${cmd}.ok ]; then
        prefix=`urlprefix ${rqueue}`

        atomicnccopy ${rqueue}/"${msgid}"/receipt.out "${pubrqueue}"/"${msgid}"
        curl -sSfg -o ${rqueue}/"${msgid}"/${cmd}.ans "${prefix}"/rcp/"${msgid}"
    else
        error "${cmd}.ok not found"
    fi
    ;;

ack)
    # <ack> [comm loop]
    if [ -e ${queue}/"${msgid}"/${cmd}.ok ]; then
        prefix=`urlprefix ${queue}`

        rm -f "${pubqueue}"/"${msgid}"

        ackhash=`cat ${queue}/"${msgid}"/receipt.ack | tr -cd '[:xdigit:]' | tr A-F a-f`
        [ ${#ackhash} = 128 ] || error "bad ackhash"

        curl -sSfg -o ${queue}/"${msgid}"/${cmd}.ans "${prefix}"/ack/"${msgid}"/"${ackhash}"

        mv -T ${queue}/"${msgid}" ${queue}/"${msgid}".trash
        rm -r --one-file-system   ${queue}/"${msgid}".trash
    else
        error "${cmd}.ok not found"
    fi
    ;;

fin)
    # <fin> [comm loop]
    if [ -e ${rqueue}/"${msgid}".trash ]; then
        rm -f "${pubrqueue}"/"${msgid}"
        rm -r --one-file-system ${rqueue}/"${msgid}".trash
    else
        error "${msgid}.trash not found"
    fi
    ;;

*)
    error "unknown command"
    ;;
esac
