#!/bin/sh -e

umask 077
export LC_ALL=C


if [ $# != 2 ]; then
    echo "Format: $0 send|recv|ack <msgid>"
    exit 1
fi


# Helpers
prefix="${0##*/}"
prefix="${0%${prefix}}"
cms="${prefix}"cms
mhdrop="${prefix}"mhdrop


# Directories
ssldir=${SECURITY_HOME}/ssl
queue=${HOME}/persist/cables/queue
rqueue=${HOME}/persist/cables/rqueue

# Parameters
cmd="$1"
msgid="$2"


error() {
    echo "crypto (${msgid}): $1" 1>&2
    exit 1
}


getuserhost() {
    username=`cat $1/"${msgid}"/username | tr -cd a-z2-7`
    hostname=`cat $1/"${msgid}"/hostname | tr -cd '[:alnum:].-' | tr '[:upper:]' '[:lower:]'`
    check_userhost "${username}" "${hostname}"
}


# Sanity checks
[ ${#msgid} = 40 ] || error "bad msgid"

check_userhost() {
    [ ${#1} = 32 ] || error "bad username"
    [ ${#2} != 0 ] || error "bad hostname"
}


case "${cmd}" in
send)
    # <send> [crypto loop]
    if [ -e ${queue}/"${msgid}"/${cmd}.rdy ]; then
        if "${cms}" ${cmd} ${ssldir} ${queue}/"${msgid}" 2>/dev/null; then
            mv ${queue}/"${msgid}"/${cmd}.rdy ${queue}/"${msgid}"/${cmd}.ok
            rm ${queue}/"${msgid}"/message
        else
            mv ${queue}/"${msgid}"/${cmd}.rdy ${queue}/"${msgid}"/${cmd}.req
            error "${cmd} failed"
        fi
    else
        error "${cmd}.rdy not found"
    fi
    ;;

recv)
    # <recv> [crypto loop]
    if [ -e ${rqueue}/"${msgid}"/${cmd}.rdy ]; then
        if "${cms}" ${cmd} ${ssldir} ${rqueue}/"${msgid}" 2>/dev/null; then
            getuserhost ${rqueue}
            date=`date -uR`

            /bin/gzip -cd ${rqueue}/"${msgid}"/message            \
                | formail -z -I 'From '                           \
                             -i "From: <${username}@${hostname}>" \
                             -I "X-Received-Date: ${date}"        \
                > ${rqueue}/"${msgid}"/message.ibx

            # Prepare headers for local MUA failure message
            formail -f -X From: -X To: -X Cc: -X Bcc: -X Subject: -X Date:         \
                    -X Message-ID: -X In-Reply-To: -X References: -a 'Subject: '   \
                < ${rqueue}/"${msgid}"/message.ibx | sed 's/^Subject: /&[fail] /i' \
                > ${rqueue}/"${msgid}"/message.hdr

            "${mhdrop}" ${rqueue}/"${msgid}"/message.ibx

            mv ${rqueue}/"${msgid}"/${cmd}.rdy ${rqueue}/"${msgid}"/${cmd}.ok
            rm ${rqueue}/"${msgid}"/message    ${rqueue}/"${msgid}"/message.out
        else
            mv ${rqueue}/"${msgid}"/${cmd}.rdy ${rqueue}/"${msgid}"/${cmd}.req
            error "${cmd} failed"
        fi
    else
        error "${cmd}.rdy not found"
    fi
    ;;

ack)
    # <ack> [crypto loop]
    if [ -e ${queue}/"${msgid}"/${cmd}.rdy ]; then
        if "${cms}" ${cmd} ${ssldir} ${queue}/"${msgid}" 2>/dev/null; then
            getuserhost ${queue}
            date=`date -uR`

            (formail -f -i "Date: ${date}" < ${queue}/"${msgid}"/message.hdr;   \
                echo "Verified message delivery to\n  ${username}@${hostname}") \
                > ${queue}/"${msgid}"/message.ack

            "${mhdrop}" ${queue}/"${msgid}"/message.ack

            mv ${queue}/"${msgid}"/${cmd}.rdy  ${queue}/"${msgid}"/${cmd}.ok
            rm ${queue}/"${msgid}"/message.out ${queue}/"${msgid}"/receipt.out \
               ${queue}/"${msgid}"/message.sig
        else
            mv ${queue}/"${msgid}"/${cmd}.rdy ${queue}/"${msgid}"/${cmd}.req
            error "${cmd} failed"
        fi
    else
        error "${cmd}.rdy not found"
    fi
    ;;

*)
    error "unknown command"
    ;;
esac
