# XDG autostart list:
# sed -n 's/^Exec=[[:blank:]]*//p' /etc/xdg/autostart/*.desktop

# Variables
prefix=${HOME}/bin/x11

# Restrict X server access
xhost -si:localuser:${USER}
xhost -

# X settings
# xrdb /dev/null
# xbacklight -set 100
xset b off s 300 15 dpms 300 600 900
xset r rate 250 50 m 3/2 0

if [ "${X11_KBD_LAYOUT}.${X11_KBD_VARIANT}" = us. ]; then
    X11_KBD_COMPOSE=ralt
fi
setxkbmap ${X11_KBD_LAYOUT:+-layout ${X11_KBD_LAYOUT}} ${X11_KBD_VARIANT:+-variant ${X11_KBD_VARIANT}} \
          ${X11_KBD_COMPOSE:+-option compose:${X11_KBD_COMPOSE}} &

# Launch daemons
# assume [ -z "${DBUS_SESSION_BUS_ADDRESS}" ]
# eval `dbus-launch --sh-syntax`
# eval `ssh-agent -s`
eval `gpg-agent -s --daemon --enable-ssh-support --options ${XDG_CONFIG_HOME}/pgp/gpg-agent.conf`

# assume [ -z "${GNOME_KEYRING_CONTROL}" ]
set -a;  eval `gnome-keyring-daemon -sdc secrets`;  set +a

# Check XDG_*_DIR directories according to
# ${XDG_CONFIG_HOME}/user-dirs.dirs contents
# xdg-user-dirs-update

# Launch window manager and export its PID
wm="openbox --sm-disable"
$wm & export WM_PID=$!

# Launch a simple compositing manager (clients crash when unsupported)
# xcompmgr -cC -r7 -o.65 -l-10 -t-8 &

# Launch WM accessories
lxpanel &

# Delay launch of other apps until the task bar is up
# (and generate wallpaper along the way)
${prefix}/gen-wallpaper
pcmanfm -d --desktop &

# Launch automatic lid-autolock
${prefix}/lid-xlock & LIDXLOCK_PID=$!

# Launch synaptics daemon (prevents accidental taps during keyboard activity)
syndaemon -d -t -k -i 2 &

# Launch clipboard, NetworkManager and Bluetooth applets (use tray -> after panel)
nm-applet --sm-disable &
bluetooth-applet &

# Launch input method daemons
# uim-toolbar-gtk-systray is squashed by lxpanel (#405025)
uim-xim --engine=direct &
uim-toolbar-gtk &

# Launch authenticating dialog agent for PolKit
/usr/libexec/polkit-gnome-authentication-agent-1 &

# Launch shared clipboard / seamless display / display resize services on VirtualBox
if VBoxControl -nologo guestproperty get /VirtualBox/HostInfo/VBoxVer 1>/dev/null 2>&1; then
    VBoxClient-all &
fi

# Wait for WM exit
wait ${WM_PID}

# Kill lid-autolock
kill ${LIDXLOCK_PID}

# Kill daemons
kill ${GNOME_KEYRING_PID}
kill `echo ${GPG_AGENT_INFO} | cut -d: -f2`
# eval `ssh-agent -s -k`
# kill ${DBUS_SESSION_BUS_PID}

# Remove X11 cookie
xauth remove ${DISPLAY}
