unset HISTFILE
HISTCONTROL=erasedups
HISTSIZE=100

alias l="ls -l"
alias ll="l -a"
alias -- -="less"
alias g="grep"
alias du="du -ks"
alias ..="cd .."

alias mcrypt='mcrypt -c ${MCRYPTRC}'

# http://lkml.org/lkml/2010/11/16/392
if [ -e /sys/fs/cgroup/user ]; then
    cgdir=`mktemp -d --tmpdir=/sys/fs/cgroup/user cg.XXXXXXXXXX` \
        && echo $$ > ${cgdir}/tasks
fi
