unset HISTFILE
HISTCONTROL=erasedups
HISTSIZE=100

alias l="ls -l"
alias ll="l -a"
alias -- -="less"
alias g="grep"
alias du="du -ks"
alias ..="cd .."

alias mcrypt='mcrypt -c ${MCRYPTRC}'

# http://lkml.org/lkml/2010/11/16/392
cgdir=`mktemp -d --tmpdir=/var/cgroup/user cg.$$.XXXXXXXXXX` \
    && echo $$ > ${cgdir}/tasks
