{ \
+change-x-forwarded-for{block} \
+hide-from-header{block} \
+hide-referer{forge} \
+overwrite-last-modified{randomize} \
+session-cookies-only \
+set-image-blocker{pattern} \
+client-header-filter{hide-tor-exit-notation} \
}
/ # Match all URLs
